<?php
$title = 'Agregar autorización SAR';
$this->headTitle($title);

$Cai=$form->get('Cai');
$Cai->setAttribute('class', 'form-control autofocus');
$Cai->setAttribute('placeholder', '6E7C83-81B02E-9E47B7-BB1747-32EAAE-47');

$Consecutivo_Inicial_Establ=$form->get('Consecutivo_Inicial_Establ');
$Consecutivo_Inicial_Establ->setAttribute('class', 'form-control');
$Consecutivo_Inicial_Establ->setAttribute('placeholder', '000');

$Consecutivo_Inicial_Punto=$form->get('Consecutivo_Inicial_Punto');
$Consecutivo_Inicial_Punto->setAttribute('class', 'form-control');
$Consecutivo_Inicial_Punto->setAttribute('placeholder', '000');

$Consecutivo_Inicial_Tipo=$form->get('Consecutivo_Inicial_Tipo');
$Consecutivo_Inicial_Tipo->setAttribute('class', 'form-control');
$Consecutivo_Inicial_Tipo->setAttribute('placeholder', '00');

$Consecutivo_Inicial_Correlativo=$form->get('Consecutivo_Inicial_Correlativo');
$Consecutivo_Inicial_Correlativo->setAttribute('class', 'form-control');
$Consecutivo_Inicial_Correlativo->setAttribute('placeholder', '00000000');

$Consecutivo_Final_Establ=$form->get('Consecutivo_Final_Establ');
$Consecutivo_Final_Establ->setAttribute('class', 'form-control');
$Consecutivo_Final_Establ->setAttribute('placeholder', '000');

$Consecutivo_Final_Punto=$form->get('Consecutivo_Final_Punto');
$Consecutivo_Final_Punto->setAttribute('class', 'form-control');
$Consecutivo_Final_Punto->setAttribute('placeholder', '000');

$Consecutivo_Final_Tipo=$form->get('Consecutivo_Final_Tipo');
$Consecutivo_Final_Tipo->setAttribute('class', 'form-control');
$Consecutivo_Final_Tipo->setAttribute('placeholder', '00');

$Consecutivo_Final_Correlativo=$form->get('Consecutivo_Final_Correlativo');
$Consecutivo_Final_Correlativo->setAttribute('class', 'form-control');
$Consecutivo_Final_Correlativo->setAttribute('placeholder', '00000000');

$Sucursal=$form->get('Sucursal');
$Sucursal->setAttribute('class', 'form-control');

$Fecha_Limite=$form->get('Fecha_Limite');
$Fecha_Limite->setAttribute('class', 'form-control');

$submit=$form->get('submit');
$submit->setAttribute('class', 'btn btn-success btn-lg btn-block');

//$form->setAttribute('action', $this->url('autorizacionsar/add'));
$form->prepare();
?> 
                                           
<section id="cover">
    <div id="cover-caption">
        <div id="container-fluid" class="container-fluid">
        <h4 class="text-center"><i class="fa fa-id-card fa-md" aria-hidden="true"></i><?= $this->escapeHtml($title) ?></h4>
            <div class="row justify-content-center">
                <div class="col-md-12 offset-md-7">
                        <?php
                        echo $this->form()->openTag($form);
                         ?>
                            <label class="text-center">Clave de autorización de impresión</label>
                            <div class="row">
                                <div class="col-md-5">
                                    <div class="form-group">
                                    <?= $this->formLabel($Cai) ?><br>
                                    <?= $this->formElement($Cai) ?>
                                    <?= $this->formElementErrors()->render($Cai, ['class' => 'help-inline  text-danger']) ?>
                                    </div>
                                </div>
                            </div>
                            <label>Número de Documento Fiscal Inicial</label>
                            <div class="row">
                                <div class="col-md-1">
                                    <div class="form-group">
                                    <?= $this->formLabel($Consecutivo_Inicial_Establ) ?><br>
                                    <?= $this->formElement($Consecutivo_Inicial_Establ) ?>
                                    <?= $this->formElementErrors()->render($Consecutivo_Inicial_Establ, ['class' => 'help-inline  text-danger']) ?>
                                    </div>
                                </div>
                                <div class="col-md-1">
                                    <div class="form-group">
                                    <?= $this->formLabel($Consecutivo_Inicial_Punto) ?><br>
                                    <?= $this->formElement($Consecutivo_Inicial_Punto) ?>
                                    <?= $this->formElementErrors()->render($Consecutivo_Inicial_Punto, ['class' => 'help-inline  text-danger']) ?>
                                    </div>
                                </div>
                                <div class="col-md-1">
                                    <div class="form-group">
                                    <?= $this->formLabel($Consecutivo_Inicial_Tipo) ?><br>
                                    <?= $this->formElement($Consecutivo_Inicial_Tipo) ?>
                                    <?= $this->formElementErrors()->render($Consecutivo_Inicial_Tipo, ['class' => 'help-inline  text-danger']) ?>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                    <?= $this->formLabel($Consecutivo_Inicial_Correlativo) ?><br>
                                    <?= $this->formElement($Consecutivo_Inicial_Correlativo) ?>
                                    <?= $this->formElementErrors()->render($Consecutivo_Inicial_Correlativo, ['class' => 'help-inline  text-danger']) ?>
                                    </div>
                                </div>
                            </div>
                            <label class="text-center">Número de Documento Fiscal Final</label>
                            <div class="row">
                                <div class="col-md-1">
                                    <div class="form-group">
                                    <?= $this->formLabel($Consecutivo_Final_Establ) ?><br>
                                    <?= $this->formElement($Consecutivo_Final_Establ) ?>
                                    <?= $this->formElementErrors()->render($Consecutivo_Final_Establ, ['class' => 'help-inline  text-danger']) ?>
                                    </div>
                                </div>
                                <div class="col-md-1">
                                    <div class="form-group">
                                    <?= $this->formLabel($Consecutivo_Final_Punto) ?><br>
                                    <?= $this->formElement($Consecutivo_Final_Punto) ?>
                                    <?= $this->formElementErrors()->render($Consecutivo_Final_Punto, ['class' => 'help-inline  text-danger']) ?>
                                    </div>
                                </div>
                                <div class="col-md-1">
                                    <div class="form-group">
                                    <?= $this->formLabel($Consecutivo_Final_Tipo) ?><br>
                                    <?= $this->formElement($Consecutivo_Final_Tipo) ?>
                                    <?= $this->formElementErrors()->render($Consecutivo_Final_Tipo, ['class' => 'help-inline  text-danger']) ?>
                                </div>
                               </div>
                               <div class="col-md-2">
                                    <div class="form-group">
                                    <?= $this->formLabel($Consecutivo_Final_Correlativo) ?><br>
                                    <?= $this->formElement($Consecutivo_Final_Correlativo) ?>
                                    <?= $this->formElementErrors()->render($Consecutivo_Final_Correlativo, ['class' => 'help-inline  text-danger']) ?>
                                     </div>
                                </div>

                            </div>
                            <div class="row">
                                <div class="col-md-2"> 
                                    <div class="form-group">
                                    <?= $this->formLabel($Sucursal) ?><br>
                                    <?= $this->formElement($Sucursal) ?>
                                    <?= $this->formElementErrors()->render($Sucursal, ['class' => 'help-inline  text-danger']) ?>
                                    </div>
                                </div>
                                <div class="col-md-3">        
                                    <div class="form-group">
                                    <?= $this->formLabel($Fecha_Limite) ?><br>
                                    <?= $this->formElement($Fecha_Limite) ?>
                                    <?= $this->formElementErrors()->render($Fecha_Limite, ['class' => 'help-inline  text-danger']) ?>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                    <div class="col-md-5">
                                    <?php
                                    echo $this->formSubmit($submit);
                                    echo $this->formHidden($form->get('Cod_Autorizacion'));
                                    ?>
                                    </div>
                            </div>
                    <?php
                        echo $this->form()->closeTag();
                    ?>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
 $('#Fecha_Limite').datepicker({
        iconsLibrary: 'fontawesome',
         footer: true,
         modal: true,
         format: 'yyyy-mm-dd',
         //locale: 'es-es'
        });
</script>