<?php
$title = 'Autorizaciones';
$this->headTitle($title);
?>
<div class="container-fluid">
    <h4 class="text-center"><i class="fa fa-file fa-md" aria-hidden="true"></i><?= $this->escapeHtml($title) ?></h4>
      <p>
        <a class="btn btn-outline-info float-right"  role="button" href="<?= $this->url('autorizacionsar/add')?>"><i class="fa fa-plus-circle"></i>Agregar</a>
      </p>
    <table class="table table-hover"    id="example"  style="width:100%">
      <thead  class="thead-light">
        <tr>
          <th>No.</th>
          <th>Sucursal</th>
          <th>Tipo documento fiscal</th>
          <th>Clave de autorización de impresión</th>
          <th>Consecutivo Inicial</th>
          <th>Consecutivo Final</th>
          <th>Consecutivo Actual</th>
          <th>Fecha l&iacute;mite de emisi&oacute;n</th>
          <th>Fecha de ingreso</th>
        </tr>
      </thead>
      <tbody>
        <?php 
        $count=1;
        foreach ($auto as $a) : ?>
        <tr>
          <td><?= $count ?></td>
          <td><?= $this->escapeHtml($a->Nombre_Sucursal) ?></td>
          <td><?= $this->escapeHtml($a->Nombre_Documento)?></td>
          <td><?= $this->escapeHtml($a->Cai) ?></td>
          <td><?= $this->escapeHtml($a->Consecutivo_Inicial_Establ."-".$a->Consecutivo_Inicial_Punto."-".$a->Consecutivo_Inicial_Tipo."-".$a->Consecutivo_Inicial_Correlativo) ?></td>
          <td><?= $this->escapeHtml($a->Consecutivo_Final_Establ."-".$a->Consecutivo_Final_Punto."-".$a->Consecutivo_Final_Tipo."-".$a->Consecutivo_Final_Correlativo)  ?></td>
          <td><?= $this->escapeHtml($a->Consecutivo_Actual_Establ."-".$a->Consecutivo_Actual_Punto."-".$a->Consecutivo_Actual_Tipo."-".$a->Consecutivo_Actual_Correlativo)?></td>
          <td><?= $this->escapeHtml($a->Fecha_Limite) ?></td>
          <td><?= $this->escapeHtml($a->Fecha_Ingreso) ?></td>
        </tr>
          <?php 
          $count++;
        endforeach; 
        ?>
      </tbody>
    </table>
<script type="text/javascript">
 $(document).ready(function() {
    $('#example').DataTable({
    "language": {
      "url": "dataTables/js/Spanish.json"
      }
    });
   });
</script>
</div>