<?php
$title = 'Agregar Constancia de Retención';
$this->headTitle($title);
$Fecha_Emision =$form->get('Fecha_Emision');
$Autorizacion_Sar=$form->get('Autorizacion_Sar');
$Autorizacion_Sar->setAttribute('readonly', 'readonly');
$Sucursal=$form->get('Sucursal');
$Sucursal->setAttribute('readonly', 'readonly');
$Usuario=$form->get('Usuario')->setValue($this->identity()['Cod_Usuario']);
$Consecutivo_Actual_Establ=$form->get('Consecutivo_Actual_Establ');
$Consecutivo_Actual_Punto=$form->get('Consecutivo_Actual_Punto');
$Consecutivo_Actual_Tipo=$form->get('Consecutivo_Actual_Tipo');
$Consecutivo_Actual_Correlativo=$form->get('Consecutivo_Actual_Correlativo');
$Tipo_Retencion=$form->get('Tipo_Retencion');
$Base_Gravable_Impuesto=$form->get('Base_Gravable_Impuesto');
$Base_Gravable_Impuesto->setAttribute('placeholder', '0');
$Base_Gravable_Impuesto->setAttribute('onkeypress','return filterFloat(event,this);');
$Importe_Retencion=$form->get('Importe_Retencion');
$Importe_Retencion->setAttribute('readonly', 'readonly');
$Importe_Retencion->setAttribute('placeholder','0');
$Proveedor=$form->get('Proveedor');
$Direccion_Proveedor=$form->get('Direccion_Proveedor');
$Documento_Retencion=$form->get('Documento_Retencion');
$No_Correlativo=$form->get('No_Correlativo');
$RTN_Proveedor=$form->get('RTN_Proveedor');
$Cai_Documento=$form->get('Cai_Documento');
$Descripcion_Tributo_Retenido=$form->get('Descripcion_Tributo_Retenido');
$Cancelar=$form->get('Cancelar');
$submit=$form->get('submit');

$form->prepare();
?>
<section id="cover">
    <div class="container">
                <div class="card">
                    <div class="card-header">
                         <h4 class="text-center"><i class="fa fa-file fa-md" aria-hidden="true"></i><?= $this->escapeHtml($title) ?></h4>
                    </div>
                    <div class="card-body">
                <?= $this->form()->openTag($form)?>
                <strong>Documento Fiscal No.</strong>
                    <div class="row">
                        <div class="col-md-1">
                          <div class="form-group">
                            <?= $this->formLabel($Consecutivo_Actual_Establ) ?>
                            <?= $this->formElement($Consecutivo_Actual_Establ) ?>
                            <?= $this->formElementErrors()->render($Consecutivo_Actual_Establ, ['class' => 'help-inline  text-danger']) ?>
                          </div>
                        </div>
                        <div class="col-md-1">
                          <div class="form-group">
                            <?= $this->formLabel($Consecutivo_Actual_Punto) ?>
                            <?= $this->formElement($Consecutivo_Actual_Punto) ?>
                            <?= $this->formElementErrors()->render($Consecutivo_Actual_Punto, ['class' => 'help-inline  text-danger']) ?>
                          </div>
                        </div>
                        <div class="col-md-1">
                          <div class="form-group">
                            <?= $this->formLabel($Consecutivo_Actual_Tipo) ?>
                            <?= $this->formElement($Consecutivo_Actual_Tipo) ?>
                            <?= $this->formElementErrors()->render($Consecutivo_Actual_Tipo, ['class' => 'help-inline  text-danger']) ?>
                          </div>
                        </div>
                        <div class="col-md-2">
                          <div class="form-group">
                            <?= $this->formLabel($Consecutivo_Actual_Correlativo) ?>
                            <?= $this->formElement($Consecutivo_Actual_Correlativo) ?>
                            <?= $this->formElementErrors()->render($Consecutivo_Actual_Correlativo, ['class' => 'help-inline  text-danger']) ?>
                          </div>
                        </div>
               </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                            <?= $this->formLabel($Autorizacion_Sar) ?>
                            <?= $this->formElement($Autorizacion_Sar) ?>
                            <?= $this->formElementErrors()->render($Autorizacion_Sar, ['class' => 'help-inline  text-danger']) ?>
                           </div>
                        </div>
                        <div class="col-md-4">
                           <div class="form-group">
                            <?= $this->formLabel($Sucursal) ?>
                            <?= $this->formElement($Sucursal) ?>
                            <?= $this->formElementErrors()->render($Sucursal, ['class' => 'help-inline  text-danger']) ?>
                           </div>
                        </div>
                         <div class="col-md-4">
                           <div class="form-group">
                            <?= $this->formLabel($Usuario) ?>
                            <?= $this->formElement($Usuario) ?>
                            <?= $this->formElementErrors()->render($Usuario, ['class' => 'help-inline  text-danger']) ?>
                           </div>
                        </div>
                    </div><br>
                    <strong>Información Proveedor</strong>
                    <div class="row">
                        <div class="col-md-4"> 
                            <div class="form-group">
                            <?= $this->formLabel($RTN_Proveedor) ?>
                            <?= $this->formElement($RTN_Proveedor) ?>
                            <?= $this->formElementErrors()->render($RTN_Proveedor, ['class' => 'help-inline  text-danger']) ?>
                            </div>
                        </div>
                        <div class="col-md-4"> 
                            <div class="form-group">
                            <?= $this->formLabel($Proveedor) ?>
                            <?= $this->formElement($Proveedor) ?>
                            <?= $this->formElementErrors()->render($Proveedor, ['class' => 'help-inline  text-danger']) ?>
                             </div>
                        </div>
                        <div class="col-md-4"> 
                            <div class="form-group">
                            <?= $this->formLabel($Direccion_Proveedor) ?>
                            <?= $this->formElement($Direccion_Proveedor) ?>
                            <?= $this->formElementErrors()->render($Direccion_Proveedor, ['class' => 'help-inline  text-danger']) ?>
                            </div>
                        </div>
                    </div>
                        <strong>Documento sobre el cual se retuvo</strong>
                        <div class="form-group">
                            <?= $this->formLabel($Tipo_Retencion) ?><br>
                            <?= $this->formElement($Tipo_Retencion) ?>
                            <?= $this->formElementErrors()->render($Tipo_Retencion, ['class' => 'help-inline  text-danger']) ?>
                        </div>
                        <div class="form-group">
                            <?= $this->formLabel($Base_Gravable_Impuesto) ?>
                            <?= $this->formElement($Base_Gravable_Impuesto) ?>
                            <?= $this->formElementErrors()->render($Base_Gravable_Impuesto, ['class' => 'help-inline  text-danger']) ?><span id="bas" class="text-info"></span>
                        </div>
                        <div class="form-group">
                            <?= $this->formLabel($Importe_Retencion) ?>
                            <?= $this->formElement($Importe_Retencion) ?>
                            <?= $this->formElementErrors()->render($Importe_Retencion, ['class' => 'help-inline  text-danger']) ?>
                            <span id="imp" class="text-info"></span>
                        </div>
                         <div class="form-group">
                            <?= $this->formLabel($Documento_Retencion) ?>
                            <?= $this->formElement($Documento_Retencion) ?>
                            <?= $this->formElementErrors()->render($Documento_Retencion, ['class' => 'help-inline  text-danger']) ?>
                          </div>
                        <div class="form-group">
                            <?= $this->formLabel($No_Correlativo) ?>
                            <?= $this->formElement($No_Correlativo) ?>
                            <?= $this->formElementErrors()->render($No_Correlativo, ['class' => 'help-inline  text-danger']) ?>
                           <span id="bas" class="text-info">*Formato 000-000-00-00000000</span>
                        </div>
                        <div class="form-group">
                            <?= $this->formLabel($Cai_Documento) ?>
                            <?= $this->formElement($Cai_Documento) ?>
                            <?= $this->formElementErrors()->render($Cai_Documento, ['class' => 'help-inline  text-danger']) ?>
                            <span class="text-info">*Formato 6E7C83-81B02E-9E47B7-BB1747-32EAAE-47</span>
                        </div>
                        <div class="form-group">
                            <?= $this->formLabel($Descripcion_Tributo_Retenido) ?>
                            <?= $this->formElement($Descripcion_Tributo_Retenido) ?>
                            <?= $this->formElementErrors()->render($Descripcion_Tributo_Retenido, ['class' => 'help-inline  text-danger']) ?>
                        </div>
                        <div class="form-group">
                            <?= $this->formLabel($Fecha_Emision) ?>
                            <?= $this->formElement($Fecha_Emision) ?>
                            <?= $this->formElementErrors()->render($Fecha_Emision, ['class' => 'help-inline  text-danger']) ?>
                        </div>
                <div class="row"> 
                    <div class="col-md-6">       
                        <!--cancelar-->
                        <div class="form-group">
                        <?= $this->formButton($Cancelar)?>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                        <!-- submit guardado-->
                        <?php
                            echo  $this->formSubmit($submit);
                            echo  $this->formHidden($form->get('Cod_Constancia'));
                        ?>
                        </div>
                    </div>
                </div>    
              <?=  $this->form()->closeTag()?> 
          </div>
        </div>
    </div>
</section>
<script type="text/javascript">
  function cancelar(){
     window.location.href="<?= $this->url('home')?>";
   }
    $(function(){
       $('#RTN_Proveedor').change(function(){
         var RTN_Proveedor = $(this).val();
         if(RTN_Proveedor){
            $.ajax({
             type: "GET",
             url: "/constanciaretencion/proveedor/" + $(this).val(),
             async: true,
             dataType: "json",
             beforeSend: function(x) {
                if(x && x.overrideMimeType) {
                   x.overrideMimeType("application/j-son;charset=UTF-8");
                }
             },
             success: function(data){
                var Nom_Pro = '';
                var Dir_Pro = '';
                   for (var i = 0; i < data.length; i++) {

                    Nom_Pro += '<option value="' + data[i].Cod_Proveedor + '">' + data[i].Nombre_Proveedor + '</option>';
                    Dir_Pro += data[i].Direccion_Proveedor;
                   }
                   $('#Proveedor').html(Nom_Pro);
                   $('#Direccion_Proveedor').val(Dir_Pro);
              }
        });
      }else{
           $('#Proveedor').html('<option value>Seleccione RTN</option>');
           $('#Direccion_Proveedor').val('Seleccione RTN');

      }});
    });

   $(function(){
         $('#Base_Gravable_Impuesto').change(function(){ 
            var Tipo_Retencion = $('input:radio[name = Tipo_Retencion]:checked').val();
            var tasa = parseFloat(Tipo_Retencion);
            var Base_Gravable_Impuesto = $(this).val();
            if (Base_Gravable_Impuesto && tasa){
                var Importe_Retencion = parseFloat((Base_Gravable_Impuesto * tasa) / 100 ).toFixed(2);
                $('#Base_Gravable_Impuesto').html(Base_Gravable_Impuesto);
                $('#Importe_Retencion').val(Importe_Retencion);
                
            }else{
                $('#Base_Gravable_Impuesto').val('0');
                $('#Importe_Retencion').val('0');
                var imp = document.getElementById("imp");
                imp.innerHTML='*Seleccione una tasa de retención e ingrese base gravable del impuesto';
                var bas = document.getElementById("bas");
                bas.innerHTML='*Use solamente dígitos y el "." como separador de decimales';

            }
        });
    });
  
  function filterFloat(evt,input){
    // Backspace = 8, Enter = 13, ‘0′ = 48, ‘9′ = 57, ‘.’ = 46, ‘-’ = 43
    var key = window.Event ? evt.which : evt.keyCode;    
    var chark = String.fromCharCode(key);
    var tempValue = input.value+chark;
    if(key >= 48 && key <= 57){
        if(filter(tempValue)=== false){
            return false;
        }else{       
            return true;
        }
    }else{
          if(key == 8 || key == 13 || key == 46 || key == 0) {            
              return true;              
          }else{
              return false;
          }
    }
}

function filter(__val__){
    var preg = /^([0-9]+\.?[0-9]{0,2})/; 
    if(preg.test(__val__) === true){
        return true;
    }else{
       return false;
    }
    
}  
function fac(e){
           tecla = (document.all) ? e.keyCode : e.which;
           if (tecla == 8){
            return true;
             }
          patron =/^[0-9-]$/;
          tecla_final = String.fromCharCode(tecla);
          return patron.test(tecla_final);
}
function ca(e){
           tecla = (document.all) ? e.keyCode : e.which;
           if (tecla == 8){
            return true;
             }
          patron =/^[A-Z0-9-]$/;
          tecla_final = String.fromCharCode(tecla);
          return patron.test(tecla_final);
}
 </script>