<?php
$title = 'Constancia de Retención';
$this->headTitle($title);
$Fecha_Emision =$form->get('Fecha_Emision');
$Autorizacion_Sar=$form->get('Autorizacion_Sar');
$Autorizacion_Sar->setAttribute('readonly', 'readonly');
$Sucursal=$form->get('Sucursal');
$Sucursal->setAttribute('disabled', 'disabled');
$Usuario=$form->get('Usuario')->setValue($this->identity()['Cod_Usuario']);
$Consecutivo_Actual_Establ=$form->get('Consecutivo_Actual_Establ');
$Consecutivo_Actual_Punto=$form->get('Consecutivo_Actual_Punto');
$Consecutivo_Actual_Tipo=$form->get('Consecutivo_Actual_Tipo');
$Consecutivo_Actual_Correlativo=$form->get('Consecutivo_Actual_Correlativo');
$Tipo_Retencion=$form->get('Tipo_Retencion');
$Tipo_Retencion->setAttribute('disabled', 'disabled');
$Base_Gravable_Impuesto=$form->get('Base_Gravable_Impuesto');
$Base_Gravable_Impuesto->setAttribute('readonly', 'readonly');
$Importe_Retencion=$form->get('Importe_Retencion');
$Importe_Retencion->setAttribute('readonly', 'readonly');
$Nombre_Proveedor=$form->get('Nombre_Proveedor');
$Nombre_Proveedor->setAttribute('readonly', 'readonly');
$Direccion_Proveedor=$form->get('Direccion_Proveedor');
$Direccion_Proveedor->setAttribute('disabled', 'disabled');
$Documento_Retencion=$form->get('Documento_Retencion');
$Documento_Retencion->setAttribute('readonly', 'readonly');
$No_Correlativo=$form->get('No_Correlativo');
$No_Correlativo->setAttribute('readonly', 'readonly');
$RTN_View=$form->get('RTN_View');
$RTN_View->setAttribute('readonly', 'readonly');
$Cai_Documento=$form->get('Cai_Documento');
$Cai_Documento->setAttribute('readonly', 'readonly');
$Descripcion_Tributo_Retenido=$form->get('Descripcion_Tributo_Retenido');
$Descripcion_Tributo_Retenido->setAttribute('readonly', 'readonly');
?>
<section>
    <div class="container">
          <div class="container">
            <table>
                <tbody>
                    <tr>
                        <td  style= "width:35%;"><img src="<?= $this->basePath('img/logoarmeria.png') ?>" class="img-responsive" style="height:40%; width:40%;display: block;margin-right: auto;margin-left:0;"></td>
                        <td style="text-align:center;width:30%">
                          <strong>FUERZAS ARMADAS DE HONDURAS</strong><br>
                          <strong>INSTITUTO DE PREVISIÓN MILITAR(IPM)</strong><br>
                          <strong>LA ARMERIA</strong><br>
                        </td>
                         <td  style= "width:35%;"><img src="<?= $this->basePath('img/logoIPM.png') ?>" class="img-responsive" style="height:20%; width:20%;display: block;margin-right: auto;margin-left:80%;"></td>
                    </tr>
                </tbody>
            </table><br>
            <table>
                <tbody>
                    <tr>
                        <td  style="text-align:left;width:40%">
                          <label>IPM :Colonia Luis landa Blvd Centro America</label><br>
                          <label>Contiguo a IMPREMA Fco. Morazán, Honduras</label><br>
                          <label>Tel: 504 2239-1441 meza@grupoipm.hn</label>
                        </td>
                        <td style="text-align:left;width:40%">
                          <?php foreach ($Suc as $g) : ?>
                          <label><?= $this->escapeHtml($g->Direccion) ?></label><br>
                          <label><?= $this->escapeHtml($g->Telefono) ?></label><br>
                          <label><?= $this->escapeHtml($g->Correo) ?></label>
                        <?php endforeach; ?>
                        </td>
                    </tr>
                </tbody>
            </table><br>
            <table>
                <thead>
                  <tr>
                    <th></th>
                    <th style="text-align: center">No.</th>
                    <th>Documento</th>
                    <th>Fiscal</th>
                    <th></th>
                    <th></th>
                  </tr>
                </thead>
                <tbody><?php foreach ($Cai as $b) : ?>
                  <tr>
                      <td width ="40%"><strong>CAI:<?= $this->escapeHtml($b->Cai) ?></strong></td>
                      <td width ="10%"><?= $this->formElement($Consecutivo_Actual_Establ)?></td>
                      <td width ="10%"><?= $this->formElement($Consecutivo_Actual_Tipo)?></td>
                      <td width ="10%"><?= $this->formElement($Consecutivo_Actual_Punto)?></td>
                      <td width ="10%"><?= $this->formElement($Consecutivo_Actual_Correlativo)?></td>
                  </tr><?php endforeach;?>
                </tbody>
            </table><br>
             <h5 style="text-align: center;font-weight: bold">CONSTANCIA DE RETENCIÓN</h5>
                <p>
                  Por medio de la presente hago constar que el Instituto de Previsión Militar(I.P.M), a través de la dependencia LA ARMERIA, con RTN: 080119003238214, designado como Agente de Retención y en cumplimiento al Artículo 50 de la ley del Impuesto sobre la Renta y Acuerdo No. DEI-217-2010, ha realizado la retención  que acontinuación se detalla.
                 </p>
               <div class="row">
                <div class="col-md-3">
                  <div class="form-group">
                      <?= $this->formLabel($Nombre_Proveedor) ?>
                  </div>
                </div>
                <div class="col-md-9">
                  <div class="form-group">
                       <?= $this->formElement($Nombre_Proveedor) ?>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-3">
                  <div class="form-group">
                      <?= $this->formLabel($RTN_View) ?>
                   </div>
                </div>
                <div class="col-md-9">
                  <div class="form-group">
                      <?= $this->formElement($RTN_View) ?>
                  </div>
                </div>
              </div>
             
              <div class="row">
                <div class="col-md-3">
                  <div class="form-group">
                     <?= $this->formLabel($Direccion_Proveedor) ?>
                  </div>
                </div>
                <div class="col-md-9">
                  <div class="form-group">
                     <?= $this->formElement($Direccion_Proveedor) ?>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-3">
                  <div class="form-group">
                     <?= $this->formLabel($Tipo_Retencion) ?><br>
                  </div>
                </div>
                <div class="col-md-9">
                  <div class="form-group">
                      <?= $this->formElement($Tipo_Retencion) ?>
                </div>
              </div>
            </div>
              <div class="row">
                <div class="col-md-3">
                  <div class="form-group">
                     <?= $this->formLabel($Base_Gravable_Impuesto) ?><br>
                  </div>
                </div>
                <div class="col-md-9">
                  <div class="form-group">
                    <?= $this->formElement($Base_Gravable_Impuesto) ?>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-3">
                  <div class="form-group">
                      <?= $this->formLabel($Importe_Retencion) ?>
                  </div>
                </div>
                <div class="col-md-9">
                  <div class="form-group">
                     <?= $this->formElement($Importe_Retencion) ?>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-3">
                  <div class="form-group">
                    <?= $this->formLabel($Documento_Retencion) ?>
                  </div>
                </div>
                <div class="col-md-9">
                  <div class="form-group">
                   <?= $this->formElement($Documento_Retencion) ?>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-3">
                  <div class="form-group">
                   <?= $this->formLabel($No_Correlativo) ?>
                  </div>
                </div>
                <div class="col-md-9">
                  <div class="form-group">
                   <?= $this->formElement($No_Correlativo) ?>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-3">
                  <div class="form-group">
                   <?= $this->formLabel($Cai_Documento) ?>
                  </div>
                </div>
                <div class="col-md-9">
                  <div class="form-group">
                  <?= $this->formElement($Cai_Documento) ?>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-3">
                  <div class="form-group">
                    <?= $this->formLabel($Descripcion_Tributo_Retenido) ?>
                  </div>
                </div>
                <div class="col-md-9">
                  <div class="form-group">
                   <?= $this->formElement($Descripcion_Tributo_Retenido) ?>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-3">
                  <div class="form-group">
                    <?= $this->formLabel($Fecha_Emision) ?>
                  </div>
                </div>
                <div class="col-md-9">
                  <div class="form-group">
                   <?= $this->formElement($Fecha_Emision) ?>
                  </div>
                </div>
              </div>
                  <p>
              Para los fines que estime conveniente el interesado, se extiende la presente :
            </p>
            <p>
             a los <?php
              setlocale(LC_TIME, "spanish");
              echo strftime("%d días del mes de %B" );
              ?> del año 2021.
            </p>
            <table width="100%">
                <tbody>
                <?php foreach ($Sar as $a) : ?>
                    <tr>
                      <td>Rango Autorizado:<?= $this->escapeHtml($a->Consecutivo_Inicial_Establ."-".$a->Consecutivo_Inicial_Punto."-".$a->Consecutivo_Inicial_Tipo."-".$a->Consecutivo_Inicial_Correlativo)?> al <?= $this->escapeHtml($a->Consecutivo_Final_Establ."-".$a->Consecutivo_Final_Punto."-".$a->Consecutivo_Final_Tipo."-".$a->Consecutivo_Final_Correlativo) ?></td>
                      <td>Fecha límite:<?= $this->escapeHtml($a->Fecha_Limite) ?></td>
                      <td>Fecha de impresión:<?= date('y-m-d H:i:s')?></td>
                     </tr>
                  <?php endforeach; ?>
                </tbody>
            </table>
            <table>
                <tbody><?php foreach ($user as $u) : ?>
                    <tr>
                      <td>
                        <label>user:<?= $this->escapeHtml($u->Cod_Usuario)?>-<?= $this->escapeHtml($u->Usuario)?></label>
                      </td>
                    </tr><?php endforeach; ?>
                </tbody>
                <tfoot>
                  <tr>
                    <td>Original: Cliente</td>
                  </tr>
                  <tr>
                    <td>Copia1: Obligado Tributario Emisor</td>
                  </tr>
                  <tr>
                    <td>Copia2: Contabilidad</td>
                  </tr>
                </tfoot>
            </table>
            <table width="100%">
                <tbody> 
                    <tr>
                      <td></td>
                      <td width="30%">
                        <a type="button"  target="_blank" class="btn btn-danger btn-md btn-block"  href="<?= $this->url('constanciaretencion/pdf',['Cod_Constancia'=>$Cod_Constancia])?>"><i class="fa fa-file-pdf-o"></i>PDF</a>
                      </td>
                      <td></td>
                    </tr>
                 </tbody>
            </table><br>
         </div>
    </div>
</section>
<script>
