<?php
$title = 'Constancias de Retención ';
$this->headTitle($title);
?>
<div class="container-fluid">
    <h4 class="text-center"><?= $this->escapeHtml($title) ?></h4>
    
    <table class="table table-hover"    id="example"  style="width:100%">
      <thead class="thead-light" style="">
        <tr>
          <th>c&oacute;digo  constancia</th>
          <th>Fecha emisión</th>
          <th>Documento fiscal</th>
          <th>Sucursal</th>
          <th>Proveedor</th>
          <th>Documento de Retención</th>
          <th>Tasa retención</th>
          <th>Base grabable del impuesto</th>
          <th>Importe de retención</th>
          <th>Acciones</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      <?php foreach ($constancias as $a) : ?>
      <tr class="text-center">
        <td><?= $this->escapeHtml($a->Cod_Constancia) ?></td>
        <td><?= $this->escapeHtml($a->Fecha_Emision) ?></td>
        <td><?= $this->escapeHtml($a->Consecutivo_Actual_Establ."-".$a->Consecutivo_Actual_Punto."-".$a->Consecutivo_Actual_Tipo."-".$a->Consecutivo_Actual_Correlativo)?></td>
        <td><?= $this->escapeHtml($a->Sucursal) ?></td>
        <td><?= $this->escapeHtml($a->Proveedor) ?></td>
        <td><?= $this->escapeHtml($a->Documento_Retencion)?></td>
        <td><?= $this->escapeHtml($a->Tipo_Retencion).'%'?></td>
        <td>
          <?Php
         $base = $this->escapeHtml($a->Base_Gravable_Impuesto);
         echo number_format($base, 2, ".", ",");
        ?>
        </td>
        <td><?Php
         $Importe = $this->escapeHtml($a->Importe_Retencion);
         echo number_format($Importe, 2, ".", ",");

        ?></td>
        <td>
            <a type="button"  class=" btn btn-info btn-block btn-md"  href="<?= $this->url('constanciaretencion/detalle',['Cod_Constancia'=>$a->Cod_Constancia])?>"><i class="fa fa-eye-slash">Ver</i></a>
        </td>
        <td>
          <a type="button"  class=" btn btn-danger btn-block btn-md" target="_blank"   href="<?= $this->url('constanciaretencion/pdf',['Cod_Constancia'=>$a->Cod_Constancia])?>"><i class="fa fa-file-pdf-o">PDF</i></a>
        </td>   
      </tr>
      <?php endforeach; ?>
     </tbody>
</table>
</div>
<script type="text/javascript">
 $(document).ready(function() {
    $('#example').DataTable({
    "language": {
      "url": "datatables/js/Spanish.json"
      }
    });
   });
</script>