<?= $this->doctype() ?>
<?php
$title = 'Constancia de Retención';
$this->headTitle($title);
$Fecha_Emision =$form->get('Fecha_Emision');
$Autorizacion_Sar=$form->get('Autorizacion_Sar');
$Autorizacion_Sar->setAttribute('readonly', 'readonly');
$Sucursal=$form->get('Sucursal');
$Sucursal->setAttribute('disabled', 'disabled');
$Usuario=$form->get('Usuario')->setValue($this->identity()['Cod_Usuario']);
$Consecutivo_Actual_Establ=$form->get('Consecutivo_Actual_Establ');
$Consecutivo_Actual_Punto=$form->get('Consecutivo_Actual_Punto');
$Consecutivo_Actual_Tipo=$form->get('Consecutivo_Actual_Tipo');
$Consecutivo_Actual_Correlativo=$form->get('Consecutivo_Actual_Correlativo');
$Tipo_Retencion=$form->get('Tipo_Retencion');
$Tipo_Retencion->setAttribute('disabled', 'disabled');
$Base_Gravable_Impuesto=$form->get('Base_Gravable_Impuesto');
$Base_Gravable_Impuesto->setAttribute('readonly', 'readonly');
$Importe_Retencion=$form->get('Importe_Retencion');
$Importe_Retencion->setAttribute('readonly', 'readonly');
$Proveedor=$form->get('Proveedor');
$Proveedor->setAttribute('disabled', 'disabled');
$Direccion_Proveedor=$form->get('Direccion_Proveedor');
$Direccion_Proveedor->setAttribute('disabled', 'disabled');
$Documento_Retencion=$form->get('Documento_Retencion');
$Documento_Retencion->setAttribute('readonly', 'readonly');
$No_Correlativo=$form->get('No_Correlativo');
$No_Correlativo->setAttribute('readonly', 'readonly');
$RTN_Proveedor=$form->get('RTN_Proveedor');
$RTN_Proveedor->setAttribute('disabled', 'disabled');
$Cai_Documento=$form->get('Cai_Documento');
$Cai_Documento->setAttribute('readonly', 'readonly');
$Descripcion_Tributo_Retenido=$form->get('Descripcion_Tributo_Retenido');
$Descripcion_Tributo_Retenido->setAttribute('readonly', 'readonly');
?>
<html lang="en">
<head>
      <meta charset="utf-8">
      <title>Constancia de Retención</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">   
       <style type="text/css">
       	  table {
           width: 100%;
          }
          td {
           text-align: left;
           vertical-align: top;
           font-size:x-small;
          }
          th{
            text-align: left;
            vertical-align: top;
            font-weight:bold;
            font-size:x-small;
          }
          label {
           display: inline-block;
           max-width: 100%;
           margin-bottom: 3px;
           font-weight:bold;
           font-size:x-small;
          }
          input{
           text-align: center;
           display: block;
           width:100%;
           height: 17px;
           padding:1px 3px;
           font-size:x-small;
           line-height: 1.42857143;
           color: #000;
           background-color: #fff;
           background-image: none;
           border: 1px solid #ccc;
           border-radius: 3px;
          -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);
          box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);
          -webkit-transition: border-color ease-in-out .15s, -webkit-box-shadow ease-in-out .15s;
          -o-transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
          transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
        }
        select{
           display: block;
           width: 100%;
           height: 17px;
           padding: 1px 3px;
           text-align: center;
           font-size:x-small;
           line-height: 1.42857143;
           color: #000;
           background-color: #fff;
           border: 1px solid #ccc;
           border-radius: 3px;
          -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);
          box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);
          -webkit-transition: border-color ease-in-out .15s, -webkit-box-shadow ease-in-out .15s;
          -o-transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
          transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
        }
         
        .pro{ 
          padding-top:10px ;
          margin-left: 300px;
        }
        input[type="radio"],
        input[type="checkbox"] {
             box-sizing: border-box;
            padding: 0;
          }
          .form-check-inline {
        display: -webkit-inline-box;
        display: -ms-inline-flexbox;
        display: inline-flex;
        -webkit-box-align: center;
        -ms-flex-align: center;
          align-items: center;
        padding-left: 0;
        margin-right: 0.75rem;
        }

       </style>
</head>
<body>
<section>
	  <div>
          <table>
                <tbody>
                    <tr>
                        <td  style= "width:30%;"><img src="http://laarmeria/img/logoarmeria.png" style="height:40px; width:100px;display: block;margin-right: auto;margin-left: auto;"></td>
                        <td style="text-align:center;width:40%">
                             <strong>FUERZAS ARMADAS DE HONDURAS</strong><br>
                             <strong>INSTITUTO DE PREVISIÓN MILITAR(IPM)</strong><br>
                             <strong>LA ARMERIA</strong>
                        </td>
                        <td  style= "width:30%;"><img src="http://laarmeria/img/logoIPM.png" style="height:60px; width:60px;display: block;margin-right:auto;margin-left:60%;"></td>
                    </tr>
                </tbody>
            </table><br>
            <table>
                <tbody>
                    <tr>
                        <td  style="text-align:left;width:40%">
                          <label>IPM :Colonia Luis landa Blvd Centro America</label><br>
                          <label>Contiguo a IMPREMA Fco. Morazán, Honduras</label><br>
                          <label>Tel: 504 2239-1441 meza@grupoipm.hn</label>
                        </td>
                        <td style="text-align:left;width:40%">
                          <?php foreach ($Suc as $g) : ?>
                          <label><?= $this->escapeHtml($g->Direccion) ?></label><br>
                          <label>Tel: <?= $this->escapeHtml($g->Telefono) ?></label><br>
                          <label>E-mail: <?= $this->escapeHtml($g->Correo) ?></label>
                        <?php endforeach; ?>
                        </td>
                    </tr>
                </tbody>
            </table>
            <table>
                <thead>
                  <tr>
                    <th></th>
                    <th style="text-align: center">No.</th>
                    <th>Documento</th>
                    <th>Fiscal</th>
                    <th></th>
                    <th></th>
                  </tr>
                </thead>
                <tbody><?php foreach ($Cai as $b) : ?>
                  <tr>
                      <td style="width:30%"><strong>CAI: <?= $this->escapeHtml($b->Cai) ?></strong></td>
                      <td style="width:8%"><?= $this->formElement($Consecutivo_Actual_Establ)?></td>
                      <td style="width:8% "><?= $this->formElement($Consecutivo_Actual_Tipo)?></td>
                      <td style="width:8%"><?= $this->formElement($Consecutivo_Actual_Punto)?></td>
                      <td style="width:10%"><?= $this->formElement($Consecutivo_Actual_Correlativo)?></td>
                      <td style="width:5%"></td>
                  </tr><?php endforeach;?>
                </tbody>
            </table>
            <h5 style="text-align: center;font-weight: bold">CONSTANCIA DE RETENCIÓN</h5>
                <p>
                  Por medio de la presente hago constar que el Instituto de Previsión Militar(I.P.M), a través de la dependencia LA ARMERIA, con RTN: 080119003238214, designado como Agente de Retención y en cumplimiento al Artículo 50 de la ley del Impuesto sobre la Renta y Acuerdo No. DEI-217-2010, ha realizado la retención  que acontinuación se detalla.
                 </p>
           
            <table>
                <tbody>
                  <tr>
                    <td style="width:30%"><?= $this->formlabel($Proveedor)?></td>
                    <td><?= $this->formElement($Proveedor)?></td>
                  </tr>
                </tbody>
            </table>
             <table>
                <tbody>
                  <tr>
                    <td style="width:30%"><?= $this->formlabel($RTN_Proveedor)?></td>
                    <td><?= $this->formElement($RTN_Proveedor)?></td>
                  </tr>
                </tbody>
            </table>
            <table>
                <tbody>
                  <tr>
                    <td style="width:30%"><?= $this->formlabel($Direccion_Proveedor)?></td>
                    <td><?= $this->formElement($Direccion_Proveedor)?></td>
                  </tr>
                </tbody>
            </table>
            <table>
                <tbody>
                  <tr>
                    <td style="width:30%"><?= $this->formlabel($Tipo_Retencion)?></td>
                    <td style="width:5%"><?= $this->formElement($Tipo_Retencion)?></td>
                    <td style="width:65%"></td>
                  </tr>
                </tbody>
            </table>
            <table>
                <tbody>
                  <tr>
                    <td style="width:30%"><?= $this->formlabel($Base_Gravable_Impuesto)?></td>
                    <td><?=$this->formElement($Base_Gravable_Impuesto)?></td>
                  </tr>
                </tbody>
            </table>
            <table>
                <tbody>
                  <tr>
                    <td style="width:30%"><?= $this->formlabel($Importe_Retencion)?></td>
                    <td><?= $this->formElement($Importe_Retencion)?></td>
                  </tr>
                </tbody>
            </table>
            <table>
                <tbody>
                  <tr>
                    <td style="width:30%"><?= $this->formlabel($Documento_Retencion)?></td>
                    <td><?= $this->formElement($Documento_Retencion)?></td>
                  </tr>
                </tbody>
            </table>
            <table>
                <tbody>
                  <tr>
                    <td style="width:30%"><?=  $this->formlabel($No_Correlativo)?></td>
                    <td><?=  $this->formElement($No_Correlativo)?></td>
                  </tr>
                </tbody>
            </table>
            <table>
                <tbody>
                  <tr>
                    <td style="width:30%"><?=  $this->formlabel($Cai_Documento)?></td>
                    <td><?=  $this->formElement($Cai_Documento)?></td>
                  </tr>
                </tbody>
            </table>
            <table>
                <tbody>
                  <tr>
                    <td style="width:30%"><?=  $this->formlabel($Descripcion_Tributo_Retenido)?></td>
                    <td><?=  $this->formElement($Descripcion_Tributo_Retenido)?></td>
                  </tr>
                </tbody>
            </table>
            <table>
                <tbody>
                  <tr>
                    <td style="width:30%"><?= $this->formlabel($Fecha_Emision)?></td>
                    <td><?= $this->formElement($Fecha_Emision)?></td>
                  </tr>
                </tbody>
            </table>
            <p>
              Para los fines que estime conveniente el interesado, se extiende la presente:
            </p>
            <p>
             a los <?php
              setlocale(LC_TIME, "spanish");
              echo strftime("%d días del mes de %B" );
              ?> del año 2021.
            </p>
             <table>
                <tbody>
                <?php foreach ($Sar as $a) : ?>
                    <tr>
                      <td>Rango Autorizado:<?= $this->escapeHtml($a->Consecutivo_Inicial_Establ."-".$a->Consecutivo_Inicial_Punto."-".$a->Consecutivo_Inicial_Tipo."-".$a->Consecutivo_Inicial_Correlativo)?> al <?= $this->escapeHtml($a->Consecutivo_Final_Establ."-".$a->Consecutivo_Final_Punto."-".$a->Consecutivo_Final_Tipo."-".$a->Consecutivo_Final_Correlativo) ?></td>
                      <td>Fecha límite:<?= $this->escapeHtml($a->Fecha_Limite) ?></td>
                      <td>Fecha de impresión:<?= date('y-m-d H:i:s')?></td>
                     </tr>
                  <?php endforeach; ?>
                </tbody>
            </table>
           <table>
                <tbody><?php foreach ($user as $u) : ?>
                    <tr>
                      <td>
                        <label>user:<?= $this->escapeHtml($u->Cod_Usuario)?>-<?= $this->escapeHtml($u->Usuario)?></label>
                      </td>
                    </tr><?php endforeach; ?>
                </tbody>
                <tfoot>
                  <tr>
                    <td>Original: Cliente</td>
                  </tr>
                  <tr>
                    <td>Copia1: Obligado Tributario Emisor</td>
                  </tr>
                  <tr>
                    <td>Copia2: Contabilidad</td>
                  </tr>
                </tfoot>
            </table>
             <table class="pro">
               <tr>
                <td>__________________________________</td>
              </tr>
              <tr>
                <td>Departamento de Finanzas</td>
              </tr>
            </table>
        </div>
     </section>
  </body>
</html>