<?php
$title = 'Usuarios';
$this->headTitle($title);
?>
<div class="container-fluid">
   <h4 class="text-center"><?= $this->escapeHtml($title) ?></h4>
      <p>
        <a class="btn btn-outline-info float-right"  role="button"  href="<?= $this->url('usuario/registro')?>"><i class="fa fa-plus-circle"></i>Agregar</a>
      </p>
    <table class="table table-hover"    id="example"  style="width:100%">
      <thead class="thead-light" >
          <tr>
            <th>C&oacute;digo </th>
            <th>Empleado</th>
            <th>Sucursal</th>
            <th>Departamento</th>
            <th>Usuario</th>
            <th>Correo</th>
            <th>Rol</th>
            <th>Estado</th>
            <th>Fecha de ingreso</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($usuario as $u) : ?>
          <tr>
            <td><?= $this->escapeHtml($u->Cod_Usuario) ?></td>
            <td><?= $this->escapeHtml($u->Cod_Empleado) ?></td>
            <td><?= $this->escapeHtml($u->Sucursal) ?></td>
            <td><?= $this->escapeHtml($u->Departamento) ?></td>
            <td><?= $this->escapeHtml($u->Usuario) ?></td>
            <td><?= $this->escapeHtml($u->Correo) ?></td>
            <td><?= $this->escapeHtml($u->Rol) ?></td>
            <td><?= $this->escapeHtml($u->Estado) ?></td>
            <td><?= $this->escapeHtml($u->Fecha_Ingreso) ?></td>
            <td>
              <a type="button" class=" btn btn-primary btn-block btn-sm"  href="<?= $this->url('usuario/edit',['Cod_Usuario'=>$u->Cod_Usuario])?>"><i class="fa fa-pencil">Editar</i></a>
            </td>
            <td>
              <a type="button" class="btn btn-danger btn-block  btn-sm"  href="<?= $this->url('usuario/restablecerclave', ['Cod_Usuario'=>$u->Cod_Usuario])?>"><i class="fa fa-lock">Restablecer contraseña</i></a>
            </td>
          </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
</div>
<script type="text/javascript">
 $(document).ready(function() {
    $('#example').DataTable({
    "language": {
      "url": "datatables/js/Spanish.json"
    }
    });
   });
</script>