<div class="container">
    <div>
        <h3 class="text-center"><i class="fa fa-user" aria-hidden="true"></i>Mi Perfil</h3>
    </div>
        <table class="table table-striped table-bordered table-hover  dt-responsive nowrap "  cellspacing="0"  id="example"  style="width:100%">
        <thead style="background-color:brown;color:white;">
        <tr>
            <th>c&oacute;digo de  empleado</th>
            <th>Usuario</th>
            <th>Correo</th>
            <th>Rol</th>
            <th>Estado</th>
            <th>Fecha de ingreso</th>

        </tr>
        </thead>
        <tbody>
    <?php foreach ($user as $u) : ?>
        <tr>
            <td><?= $this->escapeHtml($u->Cod_Empleado) ?></td>
            <td><?= $this->escapeHtml($u->Usuario) ?></td>
            <td><?= $this->escapeHtml($u->Correo) ?></td>
            <td><?= $this->escapeHtml($u->Rol) ?></td>
            <td><?= $this->escapeHtml($u->Estado) ?></td>
            <td><?= $this->escapeHtml($u->Fecha_Ingreso) ?></td>
        </tr>
    <?php endforeach; ?>
         </tbody>
         </table>
</div>