<div class="container">
    <div class="row">
            <div class="col-md-4">
                <p style="text-align: center; "><img src="<?= $this->basePath('img/perfil.jpg') ?>" height="100%" width="70%" class="img-thumbnail img-responsive" /></p>
            </div>
            <div class="col-md-4">
                 <h3 class="text-center">Mi Perfil</h3>
            </div>
        </div>

        <table class="table table-striped table-bordered table-hover  dt-responsive nowrap "  cellspacing="0"  id="example"  style="width:100%">
        <thead class="thead-light">
        <tr>
            <th>c&oacute;digo de  empleado</th>
            <th>Usuario</th>
            <th>Correo</th>
            <th>Rol</th>
            <th>Estado</th>
            <th>Sucursal</th>

        </tr>
        </thead>
        <tbody>
    <?php foreach ($user as $u) : ?>
        <tr>
            <td><?= $this->escapeHtml($u->Cod_Empleado) ?></td>
            <td><?= $this->escapeHtml($u->Usuario) ?></td>
            <td><?= $this->escapeHtml($u->Correo) ?></td>
            <td><?= $this->escapeHtml($u->Rol) ?></td>
            <td><?= $this->escapeHtml($u->Estado) ?></td>
            <td><?= $this->escapeHtml($u->Sucursal) ?></td>
        </tr>
    <?php endforeach; ?>
         </tbody>
         </table>
</div>