<?php
$title = 'AGREGAR GUÍA DE REMISIÓN';
$this->headTitle($title);
$Consecutivo_Actual_Establ=$form->get('Consecutivo_Actual_Establ');
$Consecutivo_Actual_Punto=$form->get('Consecutivo_Actual_Punto');
$Consecutivo_Actual_Tipo=$form->get('Consecutivo_Actual_Tipo');
$Consecutivo_Actual_Correlativo=$form->get('Consecutivo_Actual_Correlativo');
$Sucursal_Remitente=$form->get('Sucursal_Remitente');
$Punto_Partida=$form->get('Punto_Partida');
$Sucursal_Destino=$form->get('Sucursal_Destino');
$Punto_Destino=$form->get('Punto_Destino');
$Punto_Destino->setAttribute('readonly', 'readonly');
$Unidad_Transporte=$form->get('Unidad_Transporte');
$Conductor=$form->get('Conductor');
$Motivo_Traslado=$form->get('Motivo_Traslado');
$Autorizacion_Sar=$form->get('Autorizacion_Sar');
$Autorizacion_Sar->setAttribute('readonly', 'readonly');
$Num_Transferencia=$form->get('Num_Transferencia');
$Fecha_Inicio_Traslado=$form->get('Fecha_Inicio_Traslado');
$Fecha_Final_Traslado=$form->get('Fecha_Final_Traslado');
$Fecha_Emision = $form->get('Fecha_Emision');
$Usuario=$form->get('Usuario')->setValue($this->identity()['Cod_Usuario']);
$productos=$form->get('productos');
$Cancelar=$form->get('Cancelar');
$Agregar=$form->get('agregar');
$submit=$form->get('submit');
$form->prepare();
?>
<section id="cover">
   <?= $this->form()->openTag($form)?>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title text-center"><i class="fa fa-file fa-md" aria-hidden="true"></i><?= $this->escapeHtml($title) ?></h5>
            </div>
              <div class="card-body"> 
                <strong>Documento Fiscal No.</strong>
                  <div class="row" style="background-color:#E6E6FA">
                      <div class="col-md-1">
                          <div class="form-group">
                            <?= $this->formLabel($Consecutivo_Actual_Establ) ?>
                            <?= $this->formElement($Consecutivo_Actual_Establ) ?>
                            <?= $this->formElementErrors()->render($Consecutivo_Actual_Establ, ['class' => 'help-inline  text-danger']) ?>
                          </div>
                      </div>
                      <div class="col-md-1" style="background-color:#E6E6FA">
                          <div class="form-group">
                            <?= $this->formLabel($Consecutivo_Actual_Punto) ?>
                            <?= $this->formElement($Consecutivo_Actual_Punto) ?>
                            <?= $this->formElementErrors()->render($Consecutivo_Actual_Punto, ['class' => 'help-inline  text-danger']) ?>
                          </div>
                      </div>
                      <div class="col-md-1" style="background-color:#E6E6FA">
                          <div class="form-group">
                            <?= $this->formLabel($Consecutivo_Actual_Tipo) ?>
                            <?= $this->formElement($Consecutivo_Actual_Tipo) ?>
                            <?= $this->formElementErrors()->render($Consecutivo_Actual_Tipo, ['class' => 'help-inline  text-danger']) ?>
                          </div>
                      </div>
                      <div class="col-md-2" style="background-color:#E6E6FA">
                          <div class="form-group">
                            <?= $this->formLabel($Consecutivo_Actual_Correlativo) ?>
                            <?= $this->formElement($Consecutivo_Actual_Correlativo) ?>
                            <?= $this->formElementErrors()->render($Consecutivo_Actual_Correlativo, ['class' => 'help-inline  text-danger']) ?>
                          </div>
                      </div>
                </div><br>
                <div class="row" style="background-color:#F5F5F5">
                  <div class="col-md-3">
                        <div class="form-group">
                            <?= $this->formLabel($Sucursal_Remitente) ?>
                            <?= $this->formElement($Sucursal_Remitente) ?>
                            <?= $this->formElementErrors()->render($Sucursal_Remitente, ['class' => 'help-inline  text-danger']) ?>
                        </div>
                    </div>
                    <div class="col-md-9">
                        <div class="form-group">
                            <?= $this->formLabel($Punto_Partida) ?>
                            <?= $this->formElement($Punto_Partida) ?>
                        </div>
                    </div>
                </div>
                <div class="row" style="background-color:#F5F5F5">
                  <div class="col-md-3">
                        <div class="form-group">
                            <?= $this->formlabel($Sucursal_Destino) ?>
                            <?= $this->formElement($Sucursal_Destino) ?>
                            <?= $this->formElementErrors()->render($Sucursal_Destino, ['class' => 'help-inline  text-danger']) ?>
                        </div>
                    </div>
                    <div class="col-md-9">
                        <div class="form-group">
                            <?= $this->formLabel($Punto_Destino) ?>
                            <?= $this->formElement($Punto_Destino) ?>
                        </div>
                    </div>
                </div><br>
                <strong>Información adicional</strong>
                <div class="row" style="background-color:#F5F5F5">
                    <div class="col-md-3">
                        <div class="form-group">
                            <?= $this->formLabel($Unidad_Transporte) ?>
                            <?= $this->formElement($Unidad_Transporte) ?>
                           
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <?= $this->formLabel($Conductor) ?>
                            <?= $this->formElement($Conductor) ?>
                         
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <?= $this->formLabel($Motivo_Traslado) ?>
                            <?= $this->formElement($Motivo_Traslado) ?>
                            <?= $this->formElementErrors()->render($Motivo_Traslado, ['class' => 'help-inline  text-danger']) ?>
                           
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <?= $this->formLabel($Autorizacion_Sar) ?>
                            <?= $this->formElement($Autorizacion_Sar) ?>
                            <?= $this->formElementErrors()->render($Autorizacion_Sar, ['class' => 'help-inline  text-danger']) ?>
                        </div>
                    </div>
                </div><br>
                <div class="row" style="background-color:#F5F5F5">
                     <div class="col-md-2">
                        <div class="form-group">
                            <?= $this->formLabel($Num_Transferencia) ?>
                            <?= $this->formElement($Num_Transferencia) ?>
                            <?= $this->formElementErrors()->render($Num_Transferencia, ['class' => 'help-inline  text-danger']) ?>
                        </div>
                    </div>
                      <div class="col-md-3">
                        <div class="form-group">
                            <?= $this->formLabel($Fecha_Inicio_Traslado) ?>
                            <?= $this->formElement($Fecha_Inicio_Traslado) ?>
                            <?= $this->formElementErrors()->render($Fecha_Inicio_Traslado, ['class' => 'help-inline  text-danger']) ?>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <?= $this->formLabel($Fecha_Final_Traslado) ?>
                            <?= $this->formElement($Fecha_Final_Traslado) ?>
                            <?= $this->formElementErrors()->render($Fecha_Final_Traslado, ['class' => 'help-inline  text-danger']) ?>
                        </div>
                    </div>
                    <div class="col-md-2">
                          <div class="form-group">
                            <?= $this->formLabel($Fecha_Emision) ?>
                            <?= $this->formElement($Fecha_Emision) ?>
                            <?= $this->formElementErrors()->render($Fecha_Emision, ['class' => 'help-inline  text-danger']) ?>
                          </div>
                      </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <?= $this->formLabel($Usuario) ?>
                            <?= $this->formElement($Usuario) ?>
                            <?= $this->formElementErrors()->render($Usuario, ['class' => 'help-inline  text-danger']) ?>
                        </div>
                    </div>
                </div>
                <div class="row" style="background-color:#E6E6FA">          
                    <div class="col-md-12">
                        <table id="TablaPro" class="table">
                            <thead>
                                <tr>
                                    <th></th>  
                                    <th></th>    
                                    <th>Código</th>
                                    <th>Descripci&oacute;n</th>
                                    <th>Cantidad</th>
                                    <th>Acci&oacute;n</th>
                                </tr>
                            </thead>
                            <tbody id="ProSelected">
                            <!--Ingreso un id al tbody-->
                                <tr>
                              
                                </tr>
                            </tbody>
                        </table>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                        <!-- cancelar-->
                        <?= $this->formButton($Agregar)?>
                            <span id="limit" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <!--cancelar-->
                        <div class="form-group">
                        <?= $this->formButton($Cancelar)?>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                        <!-- guardado-->
                        <?php
                            echo  $this->formSubmit($submit);
                            echo  $this->formHidden($form->get('Cod_Boleta'));
                        ?>
                        </div>
                    </div>
                  </div>
                </div> 
          </div>
      </div>
<!-- Large modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
                    <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                   <h4 class="modal-title"><i class="fa fa-shopping-cart"></i>Agregar productos a la lista</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                       <span aria-hidden="true">&times;</span>
                    </button>            
                </div>
                <div class="modal-body">
                    <div class="form-group">
                      <?= $this->formElement($productos) ?>
                    </div>
                </div>
                <div class="modal-footer">
                     <!--Uso la funcion onclick para llamar a la funcion en javascript-->
                    <button type="button" id="blo" onclick="agregarP()" class="btn btn-primary btn-danger active btn-lg" data-dismiss="modal">Agregar</button>
                </div>
            </div>
        </div>
    </div>
    <?=  $this->form()->closeTag()?>
</section>
<script type="text/javascript">
$(document).ready(function(){
    $('#Fecha_Inicio_Traslado').datepicker({
      iconsLibrary: 'fontawesome',
      footer: true,
      modal: true,
      format: 'yyyy-mm-dd',
      //locale: 'es-es'
      });
    $('#Fecha_Final_Traslado').datepicker({
      iconsLibrary: 'fontawesome',
      footer: true,
      modal: true,
      format: 'yyyy-mm-dd',
      //locale: 'es-es',
      });
  });
  function cancelar(){
     window.location.href="<?= $this->url('home')?>";
   }

   function RefrescaProducto(){
    var ip = [];
    var i = 0;
    $('.contadorfilas').each(function(index, element){
      i++;
      ip.push({
          id_pro: $(this).val()
        });
      });
    if(i != ''){
      $('#submit').removeAttr('disabled', 'disabled');
    }else{
      $('#submit').attr('disabled', 'disabled');
    }
    if(i == 20){
      $('.blo').attr('disabled', 'disabled');
        var total = document.getElementById("limit");
          total.innerHTML='*Puede agregar un máximo de 10 tipos de productos a la lista';
    }
    if(i <  20){
      $('.blo').removeAttr('disabled', 'disabled');
        var total = document.getElementById("limit");
            total.innerHTML='';
          }
    }

   function agregarP(){
    var text = $('#pro_id').find(':selected').text(); 
    var Cod_Producto = $('#pro_id').find(':selected').val(); 

        var newtr ='<tr class="item">';
        newtr= newtr+'<td class="contadorfilas"><input type="hidden" name="Cod_Detalle[]"/><td/><td><input type="text" class="form-control" name="Cod_Producto[]" id="Cod_Producto[]" value="'+Cod_Producto+'"  required></td><td><input type="text" class="form-control" name="Descripcion[]"  id="Descripcion[]"  value="'+text+'"></td><td><input class="form-control text-center"  type="number"  min="1" max="99"  id="Cantidad[]" name="Cantidad[]" value ="1"  onkeypress="return event.target.value.length < 2" required/></td>';
         newtr= newtr+'<td><button type="button" class="btn btn-danger btn-xs remove-item"><i class="fa fa-times"></i></button></td></tr>';
        $('#ProSelected').append(newtr);
          
          RefrescaProducto(); //Refresco Productos
        
        $('.remove-item').off().click(function(e){
           $(this).parent('td').parent('tr').remove(); //En accion elimino el Producto de la Tabla
              if ($('#ProSelected tr').length == 0)
                 $('#ProSelected .no-item').slideDown(300);
            RefrescaProducto();         
        });
               
  }

 function int(e){
    tecla = (document.all) ? e.keyCode : e.which;
       if (tecla==8){
        return true;
        }
        patron =/^[1-9]+$/;
        tecla_final = String.fromCharCode(tecla);
        return patron.test(tecla_final);
    }
    
    $(function(){
       $('#Sucursal_Destino').change(function(){
         var Sucursal_Destino = $(this).val();
         if(Sucursal_Destino){
            $.ajax({
             type: "GET",
             url: "/boletasremision/sucdes/" + $(this).val(),
             async: true,
             dataType: "json",
             beforeSend: function(x) {
                if(x && x.overrideMimeType) {
                   x.overrideMimeType("application/j-son;charset=UTF-8");
                }
             },
             success: function(data){
                var Dic_Cli = '';
                   for (var i = 0; i < data.length; i++) {
                    Dic_Cli += '<option value="' + data[i].Direccion + '">' + data[i].Direccion +'</option>';
                   }
                   $('#Punto_Destino').html(Dic_Cli);
            }
        });
      }else{
           $('#Punto_Destino').html('<option value>Seleccione Destino</option>');
      }});
    }); 
</script>