<?php
$title = 'Boleta de guía de remisión';
$this->headTitle($title);

$Fecha_Emision =$form->get('Fecha_Emision');
$Fecha_Emision->setAttribute('readonly', 'readonly');

$Consecutivo_Actual_Establ=$form->get('Consecutivo_Actual_Establ');
$Consecutivo_Actual_Establ->setAttribute('readonly', 'readonly');

$Consecutivo_Actual_Punto=$form->get('Consecutivo_Actual_Punto');
$Consecutivo_Actual_Punto->setAttribute('readonly', 'readonly');

$Consecutivo_Actual_Tipo=$form->get('Consecutivo_Actual_Tipo');
$Consecutivo_Actual_Tipo->setAttribute('readonly', 'readonly');

$Consecutivo_Actual_Correlativo=$form->get('Consecutivo_Actual_Correlativo');
$Consecutivo_Actual_Correlativo->setAttribute('readonly', 'readonly');

$Motivo_Traslado=$form->get('Motivo_Traslado');
$Motivo_Traslado->setAttribute('readonly','readonly');

$Num_Transferencia=$form->get('Num_Transferencia');
$Num_Transferencia->setAttribute('readonly', 'readonly');

$Punto_Partida=$form->get('Punto_Partida');
$Punto_Partida->setAttribute('disabled', 'disabled');

$Punto_Destino=$form->get('Punto_Destino');
$Punto_Destino->setAttribute('disabled', 'disabled');

$Fecha_Inicio_Traslado=$form->get('Fecha_Inicio_Traslado');
$Fecha_Inicio_Traslado->setAttribute('readonly', 'readonly');

$Fecha_Final_Traslado=$form->get('Fecha_Final_Traslado');
$Fecha_Final_Traslado->setAttribute('readonly', 'readonly');

$Sucursal=$form->get('Sucursal');
$Sucursal->setAttribute('disabled', 'disabled');

$Unidad_Transporte=$form->get('Unidad_Transporte');
$Unidad_Transporte->setAttribute('disabled', 'disabled');

$Conductor=$form->get('Conductor');
$Conductor->setAttribute('disabled', 'disabled');

$Autorizacion_Sar=$form->get('Autorizacion_Sar');
$Autorizacion_Sar->setAttribute('readonly', 'readonly');

$Autorizacion_Sar=$form->get('Autorizacion_Sar');
$Autorizacion_Sar->setAttribute('readonly', 'readonly');

$form->prepare();
echo $this->form()->openTag($form);
?>                                              
<div class="container" style="background-color:#f2f2f2"> 
    <fieldset>
        <h3 class="text-center"><?= $this->escapeHtml($title) ?></h3>
     
    <div class="row">
        <h4>N&uacute;mero de documento fiscal</h4>
        <div class="col-md-3">
            <div class="form-group">
                <?= $this->formLabel($Consecutivo_Actual_Establ) ?>
                <?= $this->formElement($Consecutivo_Actual_Establ) ?>
            </div>
        </div>

        <div class="col-md-3">
            <div class="form-group">
                <?= $this->formLabel($Consecutivo_Actual_Punto) ?>
                <?= $this->formElement($Consecutivo_Actual_Punto) ?>
            </div>
        </div>

        <div class="col-md-3">
            <div class="form-group">
                <?= $this->formLabel($Consecutivo_Actual_Tipo) ?>
                <?= $this->formElement($Consecutivo_Actual_Tipo) ?>
            </div>
        </div>

        <div class="col-md-3">
            <div class="form-group">
                <?= $this->formLabel($Consecutivo_Actual_Correlativo) ?>
                <?= $this->formElement($Consecutivo_Actual_Correlativo) ?>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                <?= $this->formLabel($Fecha_Emision) ?>
                <?= $this->formElement($Fecha_Emision) ?>
             </div>
        </div>

        <div class="col-md-3">
            <div class="form-group">
                <?= $this->formLabel($Autorizacion_Sar) ?>
                <?= $this->formElement($Autorizacion_Sar) ?>
            </div>
        </div>

        <div class="col-md-3">
            <div class="form-group">
                <?= $this->formLabel($Fecha_Inicio_Traslado) ?>
                <?= $this->formElement($Fecha_Inicio_Traslado) ?>
            </div>
        </div>

        <div class="col-md-3">
            <div class="form-group">
                <?= $this->formLabel($Fecha_Final_Traslado) ?>
                <?= $this->formElement($Fecha_Final_Traslado) ?>
            </div>
        </div>
  </div>
  
  <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <?= $this->formLabel($Punto_Partida) ?>
                <?= $this->formElement($Punto_Partida) ?>
            </div>
        </div>
        
        <div class="col-md-4">
            <div class="form-group">
                <?= $this->formLabel($Motivo_Traslado) ?>
                <?= $this->formElement($Motivo_Traslado) ?>
            </div>
        </div>
  </div>

  <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <?= $this->formLabel($Punto_Destino) ?>
                <?= $this->formElement($Punto_Destino) ?>
             </div>
        </div>
        <div class="col-md-4">
             <div class="form-group">
                <?= $this->formLabel($Num_Transferencia) ?>
                <?= $this->formElement($Num_Transferencia) ?>
             </div>
        </div>
    
  </div>
  <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <?= $this->formLabel($Sucursal) ?>
                <?= $this->formSelect($Sucursal) ?>
            </div>
        </div>
    
        <div class="col-md-4">
            <div class="form-group">
                <?= $this->formLabel($Unidad_Transporte) ?>
                <?= $this->formElement($Unidad_Transporte) ?>
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-group">
                <?= $this->formLabel($Conductor) ?>
                <?= $this->formElement($Conductor) ?>
                <?= $this->form()->closeTag()?>
            </div>
        </div>

   </div>
           
    <div class="row">
        <h4>Lista de productos</h4>       
            <div class="col-md-12">
              <table class="table table-striped table-bordered" cellspacing="0"  style="width:100%">
                    <thead>
                      <tr>
                        <th>Código de Producto</th>
                        <th>Producto</th>
                        <th>Cantidad</th>
                      </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($detalle as $a) : ?>
                        <tr>
                        <td><?= $this->escapeHtml($a->Cod_Producto) ?></td>
                        <td><?= $this->escapeHtml($a->Nombre_Producto) ?></td>
                        <td><?= $this->escapeHtml($a->Cantidad) ?></td>
                        <?php endforeach; ?>
                    </tbody>
              </table>
            </div>
    </div>
    </fieldset>
    <fieldset>
            <table style="padding: 20px 30px;width: 100%">
                <tbody>
                    <tr>
                      <td>Entregado por:_________________________</td>
                      <td>Recibido por:_________________________</td>
                    </tr>
                </tbody>
            </table><br>
            <table style="padding: 20px 30px;">
              <?php foreach ($user as $u) : ?>
                <tbody>
                    <tr>
                      
                      <label>Emitida por:</label><label><?= $this->escapeHtml($u->Cod_Usuario)?></label><label><?= $this->escapeHtml($u->Usuario)?></label><br>
                      <td><label><?= 'Fecha de impresión:'.date('y-m-d H:i:s')?></label></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
    </fieldset>
    <fieldset style="padding-top: 20px">
    <a type="button" class="btn btn-danger btn pull-right" target="_blank"  href="<?= $this->url('boletasremision/pdf',['Cod_Boleta'=> $Cod_Boleta])?>"><span class="glyphicon glyphicon-file"></span>Crear PDF</a>
    </fieldset>
</div>