<?php
$title = 'Listado de boletas para guias de remisión';
$this->headTitle($title);
?>
<div class="container-fluid">
    <h4 class="text-center"><?= $this->escapeHtml($title) ?></h4>
      <p>
         <a class="btn btn-outline-info btn-sm float-right"  role="button" href="<?= $this->url('boletasremision/pre')?>"><i class="fa fa-plus-circle"></i>Agregar</a>
      </p>
    <table class="display"    id="example"  style="width:100%">
      <thead style="background-color:brown;color:white;">
        <tr>
          <th>Sucursal</th>
          <th>c&oacute;digo  boleta</th>
          <th>N&uacute;mero de documento fiscal</th>
          <th>Fecha  Inicio de traslado</th>
          <th>Fecha Final de traslado</th>
          <th>Fecha  Emisi&oacute;n</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody>
      <?php foreach ($Boletas as $a) : ?>
      <tr>
        <td><?= $this->escapeHtml($a->Nombre_Sucursal) ?></td>
        <td><?= $this->escapeHtml($a->Cod_Boleta) ?></td>
        <td><?= $this->escapeHtml($a->Consecutivo_Actual_Establ."-".$a->Consecutivo_Actual_Punto."-".$a->Consecutivo_Actual_Tipo."-".$a->Consecutivo_Actual_Correlativo)?></td>
        <td><?= $this->escapeHtml($a->Fecha_Inicio_Traslado)?></td>
        <td><?= $this->escapeHtml($a->Fecha_Final_Traslado)?></td>
        <td><?= $this->escapeHtml($a->Fecha_Emision) ?></td>
        <td>
            <a type="button"  class=" btn btn-info btn-md"  href="<?= $this->url('boletasremision/detalle',['Cod_Boleta'=>$a->Cod_Boleta])?>"><i class="fa fa-eye-slash"></i></a>
            <a type="button"  target="_blank" class="btn btn-danger btn-md"  href="<?= $this->url('boletasremision/pdf',['Cod_Boleta'=>$a->Cod_Boleta])?>"><i class="fa fa-file-pdf-o"></i>PDF</a>      
        </td>     
      </tr>
      <?php endforeach; ?>
     </tbody>
</table>
</div>
<script type="text/javascript">
 $(document).ready(function() {
    $('#example').DataTable({
    "language": {
      "url": "datatables/js/Spanish.json"
    }
    });
   });
</script>