<?php
$title = 'Seleccione   Sucursal';
$this->headTitle($title);
$Sucursal=$form->get('Sucursal');
$enviar=$form->get('enviar');
$form->prepare();
?>                                              
<section id="cover">
    <div id="cover-caption">
        <div id="container" class="container">
            <div class="row">
                <div class="col-md-4 offset-md-4">
                    <h4 class="text-center"><?= $this->escapeHtml($title) ?></h4>
                    <div class="info-form">
                        <?=  $this->form()->openTag($form)?><br>
                        <div class="form-group">
                        <?= $this->formElement($Sucursal) ?><br>
                        <?= $this->formElementErrors()->render($Sucursal, ['class' => 'help-inline  text-danger']) ?>
                        </div>
                        <div class="form-group">
                         <?=  $this->formSubmit($enviar)?><br>          
                        </div>
                        <?=  $this->form()->closeTag() ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>