<?php
$title = 'Seleccione   Sucursal';
$this->headTitle($title);
$Sucursal=$form->get('Sucursal');
$enviar=$form->get('enviar');
$form->prepare();
echo $this->form()->openTag($form);
?>                                              
<div class="container">
 <fieldset>
        <h3 class="text-center"><?= $this->escapeHtml($title) ?></h3>
    </fieldset>
	<div class="row">
        <div class="col-md-8 col-md-offset-4"> 
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                    <?= $this->formElement($Sucursal) ?>
                    <?= $this->formElementErrors()->render($Sucursal, ['class' => 'help-inline  text-danger']) ?>
                         
                    </div>
                </div>     
            </div>
        </div>
        <div class="col-md-8 col-md-offset-5">
            <div class="row">
               <div class="col-md-3">
                    <div class="form-group">
                    <?=  $this->formSubmit($enviar)?>          
                    <?=  $this->form()->closeTag() ?>
                    </div>
                </div>
            </div>
        </div>    
    </div>
</div>
   

