<?php
$title = 'Listado de sucursales';
$this->headTitle($title);
?>
<div class="container-fluid">
  <h4 class="text-center"><?= $this->escapeHtml($title) ?></h4>
    <p><a class="btn btn-outline-info float-right"  role="button"  href="<?= $this->url('sucursal/add')?>"><i class="fa fa-plus-circle"></i>Agregar</a></p>
      <table class="table table-hover"  id="example"  style="width:100%">
          <thead style="background-color:brown;color:white;">
            <tr>
              <th>c&oacute;digo de sucursal</th>
              <th>Nombre  Sucursal</th>
              <th>Registro Nacional Tributario (RTN)</th>
              <th>Direcci&oacute;n</th>
              <th>Correo</th>
              <th>Estado</th>
              <th>Fecha de ingreso</th>
              <th>Fecha de actualizaci&oacute;n</th>
              <th>Acci&oacute;n</th>
            </tr>
          </thead>
          <tbody>
          <?php foreach ($sucur as $suc) : ?>
            <tr>
              <td><?= $this->escapeHtml($suc->Cod_Sucursal) ?></td>
              <td><?= $this->escapeHtml($suc->Nombre_Sucursal) ?></td>
              <td><?= $this->escapeHtml($suc->RTN) ?></td>
              <td><?= $this->escapeHtml($suc->Direccion) ?></td>
              <td><?= $this->escapeHtml($suc->Correo) ?></td>
               <td><?= $this->escapeHtml($suc->Estado) ?></td>
              <td><?= $this->escapeHtml($suc->Fecha_Ingreso) ?></td>
              <td><?= $this->escapeHtml($suc->Fecha_Actualizacion) ?></td>
              <td>
                <a type="button" class="btn btn-primary btn-block btn-sm"  href="<?=$this->url('sucursal/edit',['Cod_Sucursal'=>$suc->Cod_Sucursal])?>"><i class="fa fa-pencil">Editar</i></a>     
              </td>
            </tr>
          <?php endforeach; ?>
          </tbody>
        </table>
</div>
<script type="text/javascript">
 $(document).ready(function() {
    $('#example').DataTable({
    "language": {
      "url": "datatables/js/Spanish.json"
    }
    });
   });
</script>