<?php
$title = 'Listado de sucursales';
$this->headTitle($title);
?>
<div class="container">
<h2><?= $this->escapeHtml($title) ?></h2>
<div>
   <p>
      <a class="btn btn-success menu" href="<?= $this->url('sucursal/add')?>"><span class="glyphicon glyphicon-plus">Agregar</a></span></a>
   </p>
</div>
<table class="table table-striped table-bordered table-hover  dt-responsive nowrap" cellspacing="0"  id="example"  style="width:100%">
<thead style="background-color:brown;color:white;">
     <tr>
        <th>c&oacute;digo de sucursal</th>
        <th>Nombre  Sucursal</th>
        <th>RTN</th>
        <th>Direcci&oacute;n</th>
        <th>Fecha de ingreso</th>
        <th>Fecha de actualizaci&oacute;n</th>
        <th>Acci&oacute;n</th>
    </tr>
</thead>
<tbody>
<?php foreach ($sucur as $suc) : ?>
    <tr>
        <td><?= $this->escapeHtml($suc->Cod_Sucursal) ?></td>
        <td><?= $this->escapeHtml($suc->Nombre_Sucursal) ?></td>
        <td><?= $this->escapeHtml($suc->RTN) ?></td>
        <td><?= $this->escapeHtml($suc->Direccion) ?></td>
        <td><?= $this->escapeHtml($suc->Fecha_Ingreso) ?></td>
        <td><?= $this->escapeHtml($suc->Fecha_Actualizacion) ?></td>
        <td>
             <a type="button" class="btn btn-primary btn-sm"  href="<?=$this->url('sucursal/edit',['Cod_Sucursal'=>$suc->Cod_Sucursal])?>"><span class="glyphicon glyphicon-pencil"></span>Editar</a>     
        </td>
    </tr>
<?php endforeach; ?>
</tbody>
</table>
</div>
<script type="text/javascript">
 $(document).ready(function() {
    $('#example').DataTable({
    "language": {
      "url": "datatable/Spanish.json"
    }
    });
   });
</script>


  


  
  
  
        
        
