<?php
$title = 'Editar Proveedor';
$this->headTitle($title);

$Nombre_Proveedor=$form->get('Nombre_Proveedor');
$Nombre_Proveedor->setAttribute('class', 'form-control autofocus');

$Direccion_Proveedor=$form->get('Direccion_Proveedor');
$Direccion_Proveedor->setAttribute('class', 'form-control autofocus');

$Telefono_Proveedor=$form->get('Telefono_Proveedor');
$Telefono_Proveedor->setAttribute('class', 'form-control autofocus');

$RTN_Proveedor=$form->get('RTN_Proveedor');
$RTN_Proveedor->setAttribute('class', 'form-control autofocus');
$RTN_Proveedor->setAttribute('placeholder', '0000000000000');

$Cai_Proveedor=$form->get('Cai_Proveedor');
$Cai_Proveedor->setAttribute('class', 'form-control autofocus');

$submit=$form->get('submit');
$submit->setAttribute('class', 'btn btn-success btn-lg btn-block');

//$form->setAttribute('action', $this->url('departamento/add'));
$form->prepare();
?>                                                    
<section id="cover">
    <div id="cover-caption">
        <div id="container" class="container">
        <h4 class="text-center"><i class="fa fa-id-card fa-md" aria-hidden="true"></i><?= $this->escapeHtml($title) ?></h4>
            <div class="row justify-content-center">
                <div class="col-md-12 offset-md-7">
                    <div class="info-form">
                    <?= $this->form()->openTag($form)?>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <?= $this->formLabel($Nombre_Proveedor) ?>
                                    <?= $this->formElement($Nombre_Proveedor) ?>
                                    <?= $this->formElementErrors()->render($Nombre_Proveedor, ['class' => 'help-inline  text-danger']) ?>
                                </div>


                                <div class="form-group">
                                    <?= $this->formLabel($Direccion_Proveedor) ?>
                                    <?= $this->formElement($Direccion_Proveedor) ?>
                                    <?= $this->formElementErrors()->render($Direccion_Proveedor, ['class' => 'help-inline  text-danger']) ?>
                                </div>

                                <div class="form-group">
                                    <?= $this->formLabel($Telefono_Proveedor) ?>
                                    <?= $this->formElement($Telefono_Proveedor) ?>
                                    <?= $this->formElementErrors()->render($Telefono_Proveedor, ['class' => 'help-inline  text-danger']) ?>
                                </div>

                                <div class="form-group">
                                    <?= $this->formLabel($RTN_Proveedor) ?>
                                    <?= $this->formElement($RTN_Proveedor) ?>
                                    <?= $this->formElementErrors()->render($RTN_Proveedor, ['class' => 'help-inline  text-danger']) ?>
                                </div>

                                <div class="form-group">
                                    <?= $this->formLabel($Cai_Proveedor) ?>
                                    <?= $this->formElement($Cai_Proveedor) ?>
                                    <?= $this->formElementErrors()->render($Cai_Proveedor, ['class' => 'help-inline  text-danger']) ?>
                                </div>
                                <div class="form-group">
                                    <?php
                                        echo $this->formSubmit($submit);
                                        echo $this->formHidden($form->get('Cod_Proveedor'));
                                     ?> 
                                </div>
                            </div>
                        </div>
                    <?= $this->form()->closeTag()?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>