<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
      <?= $this->headTitle('La Armería')->setSeparator(' |')->setAutoEscape(false) ?>
      <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, shrink-to-fit=no')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
      ?>

      <!-- Le styles -->
      <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('bootstrap4/css/style.css'))
            ->prependStylesheet($this->basePath('bootstrap4/css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('datatables/css/jquery.dataTables.min.css'))
            ->prependStylesheet($this->basePath('font-awesome/css/font-awesome.css'))
            ->prependStylesheet($this->basePath('bootstrap4/css/gijgo.min.css'))
            ->prependStylesheet($this->basePath('bootstrap4/css/sweetalert.css'))
      ?>
      <?= $this->inlineScript()
          ->appendFile($this->basePath('bootstrap4/js/jquery-3.3.1.min.js'))
          ->appendFile($this->basePath('bootstrap4/js/bootstrap.min.js'))
          ->appendFile($this->basePath('datatables/js/jquery.dataTables.min.js'))
          ->appendFile($this->basePath('datatables/js/dataTables.bootstrap.min.js'))
          ->appendFile($this->basePath('bootstrap4/js/gijgo.min.js'))
          ->appendFile($this->basePath('bootstrap4/js/sweetalert-dev.js'))
      ?> 
</head>
<body>
    <div class="container-fluid">
        <p><h3 class="text-left zf-brown">Nombre<span class="zf-green">app</span></h3></p>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="<?= $this->url('home')?>"><i class="fa fa-home" aria-hidden="true" style=""></i>Inicio <span class="sr-only">(current)</span></a>
                </li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <?php  
                if($this->identity()):
                if($this->identity()['Rol'] == 'Invitado'){
                ?>
                 <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fa fa-file" aria-hidden="true"></i>Documentos Fiscales
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="<?= $this->url('boletacompra/add',['Sucursal'=>$this->identity()['Sucursal']])?>"><i class="fa fa-file" aria-hidden="true" ></i>Boleta compra</a>
                  <a class="dropdown-item" href="<?= $this->url('boletasremision/add',['Sucursal_Remitente'=>$this->identity()['Sucursal']])?>"><i class="fa fa-file-text" aria-hidden="true"></i>Boleta  guía de remisión</a>
                  <a class="dropdown-item" href="<?= $this->url('home')?>"><i class="fa fa-file" aria-hidden="true"></i>Constancia de retención</a>
                  <a class="dropdown-item" href="<?= $this->url('home')?>"><i class="fa fa-file" aria-hidden="true"></i>Nota de débito</a>
                  </div>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user" aria-hidden="true" style=""></i>
                   <?= $this->identity()['Correo'] ?>
                   </a>
                      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="<?= $this->url('usuario/perfil',['Cod_Usuario'=>$this->identity()['Cod_Usuario']])?>"><i class="fa fa-user" aria-hidden="true"></i>Perfil</a>
                      <a class="dropdown-item" href="<?= $this->url('logout')?>"><i class="fa fa-cog" aria-hidden="true"></i>Cerrar Sesión</a>
                      </div>
                </li>
                <?php 
                }elseif ($this->identity()['Rol'] == 'Miembro'){
                ?> 
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fa fa-file" aria-hidden="true"></i>Documentos Fiscales
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="<?= $this->url('boletacompra/add',['Sucursal'=>$this->identity()['Sucursal']])?>"><i class="fa fa-file" aria-hidden="true" ></i>Boleta compra</a>
                  <a class="dropdown-item" href="<?= $this->url('boletasremision/add',['Sucursal_Remitente'=>$this->identity()['Sucursal']])?>"><i class="fa fa-file-text" aria-hidden="true"></i>Boleta guía de remisión</a>
                  <a class="dropdown-item" href="<?= $this->url('home')?>"><i class="fa fa-file" aria-hidden="true"></i>Constancia de retención</a>
                  <a class="dropdown-item" href="<?= $this->url('home')?>"><i class="fa fa-file" aria-hidden="true"></i>Nota de débito</a>
                  </div>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user" aria-hidden="true" style=""></i>
                   <?= $this->identity()['Correo'] ?>
                   </a>
                      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="<?= $this->url('usuario/perfil',['Cod_Usuario'=>$this->identity()['Cod_Usuario']])?>"><i class="fa fa-user" aria-hidden="true"></i>Perfil</a>
                      <a class="dropdown-item" href="<?= $this->url('logout')?>"><i class="fa fa-cog" aria-hidden="true"></i>Cerrar Sesión</a>
                      </div>
                </li>
                <?php 
                }elseif ($this->identity()['Rol'] == 'Especial'){
                ?>
                 <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fa fa-file" aria-hidden="true"></i>Documentos Fiscales
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="<?= $this->url('boletacompra/add',['Sucursal'=>$this->identity()['Sucursal']])?>"><i class="fa fa-file" aria-hidden="true" ></i>Boleta  compra</a>
                  <a class="dropdown-item" href="<?= $this->url('boletasremision/add',['Sucursal_Remitente'=>$this->identity()['Sucursal']])?>"><i class="fa fa-file-text" aria-hidden="true"></i>Boleta  guía de remisión</a>
                  <a class="dropdown-item" href="<?= $this->url('constanciaretencion/add',['Sucursal'=>$this->identity()['Sucursal']])?>"><i class="fa fa-file" aria-hidden="true"></i>Constancia de retención</a>
                  <a class="dropdown-item" href="<?= $this->url('home')?>"><i class="fa fa-file" aria-hidden="true"></i>Nota de débito</a>
                  </div>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-cog" aria-hidden="true" style=""></i>Administración
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="<?= $this->url('sucursal')?>"><i class="fa fa-building" aria-hidden="true" ></i>Sucursales</a>
                    <a class="dropdown-item" href="<?= $this->url('departamento')?>"><i class="fa fa-file" aria-hidden="true" ></i>Departamentos</a>
                    <a class="dropdown-item" href="<?= $this->url('proveedor')?>"><i class="fa fa-file" aria-hidden="true" ></i>Proveedores</a>
                    <a class="dropdown-item" href="<?= $this->url('conductor')?>"><i class="fa fa-id-card" aria-hidden="true" ></i>Conductores</a>
                    <a class="dropdown-item" href="<?= $this->url('unidadtransporte')?>"><i class="fa fa-truck" aria-hidden="true"></i>Unidades de transporte</a>
                    <a class="dropdown-item" href="<?= $this->url('productos')?>"><i class="fa fa-shopping-car" aria-hidden="true"></i>Productos</a>
                    <a class="dropdown-item" href="<?= $this->url('autorizacionsar')?>"><i class="fa fa-file" aria-hidden="true" ></i>Autorisación SAR</a>
                    <a class="dropdown-item" href="<?= $this->url('boletasremision')?>"><i class="fa fa-file-text" aria-hidden="true"></i>Boletas de remisión</a>
                  </div>
                 </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user" aria-hidden="true" style=""></i>
                  <?= $this->identity()['Correo'] ?>
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="<?= $this->url('usuario/perfil',['Cod_Usuario'=>$this->identity()['Cod_Usuario']])?>"><i class="fa fa-user" aria-hidden="true"></i>Perfil</a>
                   <a class="dropdown-item" href="<?= $this->url('logout')?>"><i class="fa fa-cog" aria-hidden="true"></i>Cerrar Sesión</a>
                   </div>
                </li>
                <?php  
                }elseif($this->identity()['Rol'] == 'Admin'){ 
                ?>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fa fa-file" aria-hidden="true"></i>Consultas Documentos Fiscales
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                 <a class="dropdown-item" href="<?= $this->url('boletacompra')?>"><i class="fa fa-file" aria-hidden="true" ></i>Consultas Boleta  compra</a>
                  <a class="dropdown-item" href="<?= $this->url('boletasremision')?>"><i class="fa fa-file-text" aria-hidden="true"></i>Consultas Boleta guía de remisión</a>
                  <a class="dropdown-item" href="<?= $this->url('constanciaretencion')?>"><i class="fa fa-file" aria-hidden="true"></i>Consultas Constancia de retención</a>
                  <a class="dropdown-item" href="<?= $this->url('home')?>"><i class="fa fa-file" aria-hidden="true"></i>Nota de débito</a>
                  </div>
                </li>
                 <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fa fa-file" aria-hidden="true"></i>Emisión Documentos Fiscales
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                 <a class="dropdown-item" href="<?= $this->url('boletacompra/add',['Sucursal'=>$this->identity()['Sucursal']])?>"><i class="fa fa-file" aria-hidden="true" ></i>Boleta compra</a>
                  <a class="dropdown-item" href="<?= $this->url('boletasremision/add',['Sucursal_Remitente'=>$this->identity()['Sucursal']])?>"><i class="fa fa-file-text" aria-hidden="true"></i>Boleta  guía de remisión</a>
                  <a class="dropdown-item" href="<?= $this->url('constanciaretencion/add',['Sucursal'=>$this->identity()['Sucursal']])?>"><i class="fa fa-file" aria-hidden="true"></i>Constancia de retención</a>
                  <a class="dropdown-item" href="<?= $this->url('home')?>"><i class="fa fa-file" aria-hidden="true"></i>Nota de débito</a>
                  </div>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fa fa-cog" aria-hidden="true" style=""></i>Administración
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="<?= $this->url('usuario')?>"><i class="fa fa-user-circle-o" aria-hidden="true" ></i>Usuarios</a>
                  <a class="dropdown-item" href="<?= $this->url('sucursal')?>"><i class="fa fa-building" aria-hidden="true" ></i>Sucursales</a>
                  <a class="dropdown-item" href="<?= $this->url('departamento')?>"><i class="fa fa-file" aria-hidden="true" ></i>Departamentos</a>
                   <a class="dropdown-item" href="<?= $this->url('proveedor')?>"><i class="fa fa-file" aria-hidden="true" ></i>Proveedores</a>
                  <a class="dropdown-item" href="<?= $this->url('conductor')?>"><i class="fa fa-id-card fa-md" aria-hidden="true" ></i>Conductores</a>
                  <a class="dropdown-item" href="<?= $this->url('unidadtransporte')?>"><i class="fa fa-truck" aria-hidden="true"></i>Unidades de transporte</a>
                  <a class="dropdown-item" href="<?= $this->url('productos')?>"><i class="fa fa-shopping-cart" aria-hidden="true"></i>Productos</a>
                  <a class="dropdown-item" href="<?= $this->url('autorizacionsar')?>"><i class="fa fa-file" aria-hidden="true" ></i>Autorisación SAR</a>
                  </div>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user" aria-hidden="true" style=""></i>
                  <?= $this->identity()['Correo'] ?>
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="<?= $this->url('usuario/perfil',['Cod_Usuario'=>$this->identity()['Cod_Usuario']])?>"><i class="fa fa-user" aria-hidden="true"></i>Perfil</a>
                  <a class="dropdown-item" href="<?= $this->url('logout')?>"><i class="fa fa-cog" aria-hidden="true"></i>Cerrar Sesión</a>
                  </div>
                </li>
                <?php        
                }else{
                ?>
                <li class="nav-item">
                  <a class="nav-link" href="<?= $this->url('login') ?>"><i class="fa fa-cog" aria-hidden="true" style=""></i>Inicie sesi&oacute;n</a>
                </li>
                <?php 
                }else: 
                ?>
                <li class="nav-item">
                  <a class="nav-link"  href="<?= $this->url('login') ?>"><i class="fa fa-cog" aria-hidden="true" style=""></i>Inicie sesi&oacute;n</a>
                </li>
                <?php  endif; ?>
              </ul>
            </div>
        </nav>
      <div class="mt-4">
      <?= $this->content ?>
      <footer  class="mt-5 d-flex justify-content-end">
          <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
      </footer>
      </div>
</body>
</html>