<?php
$title = 'Editar Departamento';
$this->headTitle($title);

$Cod_Departamento=$form->get('Cod_Departamento');
$Cod_Departamento->setAttribute('class', 'form-control');
$Cod_Departamento->setAttribute('readonly', 'readonly');

$Nombre_Depto=$form->get('Nombre_Depto');
$Nombre_Depto->setAttribute('class', 'form-control');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary btn-lg btn-block');

//$form->setAttribute('action', $this->url('departamento/edit', ['Cod_Departamento'=> $Cod_Departamento]));

$form->prepare();

echo $this->form()->openTag($form);
?>
<section id="cover">
    <div id="cover-caption">
        <div id="container" class="container">
        <h4 class="text-center"><i class="fa fa-file" aria-hidden="true"></i><?= $this->escapeHtml($title) ?></h4>
            <div class="row justify-content-center">
                <div class="col-md-12 offset-md-7">
                    <div class="info-form">
                        <?= $this->form()->openTag($form)?>
                           <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <?= $this->formLabel($Cod_Departamento) ?>
                                        <?= $this->formElement($Cod_Departamento) ?>
                                        <?= $this->formElementErrors()->render($Cod_Departamento, ['class' => 'help-inline  text-danger']) ?>
                                        <?= $this->flashMessenger()->render('error', ['class' => 'help-inline  text-danger'])?>
                                    </div>

                                    <div class="form-group">
                                        <?= $this->formLabel($Nombre_Depto) ?>
                                        <?= $this->formElement($Nombre_Depto) ?>
                                        <?= $this->formElementErrors()->render($Nombre_Depto, ['class' => 'help-inline  text-danger']) ?>
                                    </div>

                                        <?= $this->formSubmit($submit)?>
                                </div>
                            </div>
                        <?= $this->form()->closeTag()?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section> 