<?php
$title = 'Agregar Boleta de Compra';
$this->headTitle($title);
$Fecha_Emision =$form->get('Fecha_Emision');
$Consecutivo_Actual_Establ=$form->get('Consecutivo_Actual_Establ');
$Consecutivo_Actual_Punto=$form->get('Consecutivo_Actual_Punto');
$Consecutivo_Actual_Tipo=$form->get('Consecutivo_Actual_Tipo');
$Consecutivo_Actual_Correlativo=$form->get('Consecutivo_Actual_Correlativo');
$Sucursal=$form->get('Sucursal');
$Sucursal->setAttribute('readonly', 'readonly');
$Proveedor=$form->get('Proveedor');
$Direccion_Proveedor=$form->get('Direccion_Proveedor');
$Telefono_Proveedor=$form->get('Telefono_Proveedor');
$RTN_Proveedor=$form->get('RTN_Proveedor');
$No_Registro_Sag=$form->get('No_Registro_Sag');
$No_Orden_Compra_Exenta=$form->get('No_Orden_Compra_Exenta');
$No_Constancia_Registro_Exonerado=$form->get('No_Constancia_Registro_Exonerado');
$Autorizacion_Sar=$form->get('Autorizacion_Sar');
$Autorizacion_Sar->setAttribute('readonly', 'readonly');
$Usuario=$form->get('Usuario')->setValue($this->identity()['Cod_Usuario']);
$Agregar=$form->get('agregar');
$Cancelar=$form->get('Cancelar');
$submit=$form->get('submit');
$form->prepare();
?>
<section id="cover">
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title text-center"><i class="fa fa-file fa-md" aria-hidden="true"></i><?= $this->escapeHtml($title) ?></h5>
            </div>
            <div class="card-body">                                            
                <?= $this->form()->openTag($form)?>
                <strong>Documento Fiscal No.</strong>
                <div class="row">
                      <div class="col-md-1">
                          <div class="form-group">
                            <?= $this->formLabel($Consecutivo_Actual_Establ) ?>
                            <?= $this->formElement($Consecutivo_Actual_Establ) ?>
                            <?= $this->formElementErrors()->render($Consecutivo_Actual_Establ, ['class' => 'help-inline  text-danger']) ?>
                          </div>
                      </div>
                      <div class="col-md-1">
                          <div class="form-group">
                            <?= $this->formLabel($Consecutivo_Actual_Punto) ?>
                            <?= $this->formElement($Consecutivo_Actual_Punto) ?>
                            <?= $this->formElementErrors()->render($Consecutivo_Actual_Punto, ['class' => 'help-inline  text-danger']) ?>
                          </div>
                      </div>
                      <div class="col-md-1">
                          <div class="form-group">
                            <?= $this->formLabel($Consecutivo_Actual_Tipo) ?>
                            <?= $this->formElement($Consecutivo_Actual_Tipo) ?>
                            <?= $this->formElementErrors()->render($Consecutivo_Actual_Tipo, ['class' => 'help-inline  text-danger']) ?>
                          </div>
                      </div>
                      <div class="col-md-2">
                          <div class="form-group">
                            <?= $this->formLabel($Consecutivo_Actual_Correlativo) ?>
                            <?= $this->formElement($Consecutivo_Actual_Correlativo) ?>
                            <?= $this->formElementErrors()->render($Consecutivo_Actual_Correlativo, ['class' => 'help-inline  text-danger']) ?>
                          </div>
                      </div>
                </div><br>
                <strong>Información de proveedor</strong>
                <div class="row" style="background-color:#F5F5F5">
                   <div class="col-md-4">
                        <div class="form-group">
                            <?= $this->formLabel($RTN_Proveedor) ?>
                            <?= $this->formElement($RTN_Proveedor) ?>
                            <?= $this->formElementErrors()->render($RTN_Proveedor, ['class' => 'help-inline  text-danger']) ?>
                           
                        </div>
                    </div>
                  <div class="col-md-2">
                        <div class="form-group">
                            <?= $this->formLabel($Proveedor) ?>
                            <?= $this->formElement($Proveedor) ?>
                            <?= $this->formElementErrors()->render($Proveedor, ['class' => 'help-inline  text-danger']) ?>
                           
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <?= $this->formLabel($Direccion_Proveedor) ?>
                            <?= $this->formElement($Direccion_Proveedor) ?>
                            <?= $this->formElementErrors()->render($Direccion_Proveedor, ['class' => 'help-inline  text-danger']) ?>
                           
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <?= $this->formLabel($Telefono_Proveedor) ?>
                            <?= $this->formElement($Telefono_Proveedor) ?>
                            <?= $this->formElementErrors()->render($Telefono_Proveedor, ['class' => 'help-inline  text-danger']) ?>
                           
                        </div>
                    </div>
                </div><br>
                <strong>Datos del Adquiriente exónerado (*Opcional)</strong>
                <div class="row" style="background-color:#F5F5F5">
                  <div class="col-md-4">
                        <div class="form-group">
                            <?= $this->formLabel($No_Registro_Sag) ?>
                            <?= $this->formElement($No_Registro_Sag) ?>
                            <?= $this->formElementErrors()->render($No_Registro_Sag, ['class' => 'help-inline  text-danger']) ?>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <?= $this->formLabel($No_Orden_Compra_Exenta) ?>
                            <?= $this->formElement($No_Orden_Compra_Exenta) ?>
                            <?= $this->formElementErrors()->render($No_Orden_Compra_Exenta, ['class' => 'help-inline  text-danger']) ?>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <?= $this->formLabel($No_Constancia_Registro_Exonerado) ?>
                            <?= $this->formElement($No_Constancia_Registro_Exonerado) ?>
                            <?= $this->formElementErrors()->render($No_Constancia_Registro_Exonerado, ['class' => 'help-inline  text-danger']) ?>
                        </div>
                    </div>
                </div><br>
                <strong>Datos adicionales</strong>
                <div class="row"  style="background-color:#F5F5F5">
                    <div class="col-md-3">
                        <div class="form-group">
                            <?= $this->formLabel($Usuario) ?>
                            <?= $this->formElement($Usuario) ?>
                            <?= $this->formElementErrors()->render($Usuario, ['class' => 'help-inline  text-danger']) ?>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <?= $this->formLabel($Sucursal) ?>
                            <?= $this->formElement($Sucursal) ?>
                            <?= $this->formElementErrors()->render($Sucursal, ['class' => 'help-inline  text-danger']) ?>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <?= $this->formLabel($Autorizacion_Sar) ?>
                            <?= $this->formElement($Autorizacion_Sar) ?>
                            <?= $this->formElementErrors()->render($Autorizacion_Sar, ['class' => 'help-inline  text-danger']) ?>
                        </div>
                    </div>
                     <div class="col-md-3">
                          <div class="form-group">
                            <?= $this->formLabel($Fecha_Emision) ?>
                            <?= $this->formElement($Fecha_Emision) ?>
                            <?= $this->formElementErrors()->render($Fecha_Emision, ['class' => 'help-inline  text-danger']) ?>
                          </div>
                      </div>
                </div>
                <strong>Lista de productos</strong> 
                <div class="row">         
                    <div class="col-md-12">
                        <table id="TablaPro" class="table">
                            <thead>
                                <tr>
                                    <td></td>
                                    <th>C&oacute;digo</th>
                                    <th>Descripci&oacute;n</th>
                                    <th>Cantidad</th>
                                    <th>Precio</th>
                                    <th>Subtotal</th>
                                    <th>Acci&oacute;n</th>
                                </tr>
                            </thead>
                            <tbody id="ProSelected">
                              <!--Ingreso al tbody-->
                                <tr>
                    
                                </tr>
                                <tr>
                                    <td><span id="Cantidad"></span></td>
                                    <td><span id="Precio"></span></td>
                                    <td><span id="Subtotal"></span></td>
                                 </tr>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="4"></td>
                                    <td>Total</td>
                                    <td><span id="total">0</span>
                                    <?= $this->formHidden($form->get('Total'))?></td>
                                 </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                        <!-- cancelar-->
                        <?= $this->formButton($Agregar)?>
                            <span id="limit" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <!--cancelar-->
                        <div class="form-group">
                        <?= $this->formButton($Cancelar)?>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                        <!-- guardado-->
                        <?php
                            echo  $this->formSubmit($submit);
                            echo  $this->formHidden($form->get('Cod_Boleta_Compra'));
                        ?>
                        </div>
                    </div>
                </div>
            </div>
              <?=  $this->form()->closeTag()?> 
        </div>
     </div>
</section>
<script type="text/javascript">
  function cancelar(){
     window.location.href="<?= $this->url('home')?>";
   }
   $(function(){
       $('#RTN_Proveedor').change(function(){
         var RTN_Proveedor = $(this).val();
         if(RTN_Proveedor){
            $.ajax({
             type: "GET",
             url: "/constanciaretencion/proveedor/" + $(this).val(),
             async: true,
             dataType: "json",
             beforeSend: function(x) {
                if(x && x.overrideMimeType) {
                   x.overrideMimeType("application/j-son;charset=UTF-8");
                }
             },
             success: function(data){
                var Nom_Pro = '';
                var Dir_Pro = '';
                var Tel_Pro = '';
                   for (var i = 0; i < data.length; i++) {

                    Nom_Pro += '<option value="' + data[i].Cod_Proveedor + '">' + data[i].Nombre_Proveedor + '</option>';
                    Dir_Pro += data[i].Direccion_Proveedor;
                    Tel_Pro += data[i].Telefono_Proveedor;
                   }
                   $('#Proveedor').html(Nom_Pro);
                   $('#Direccion_Proveedor').val(Dir_Pro);
                   $('#Telefono_Proveedor').val(Tel_Pro);
            }
        });
      }else{
           $('#Proveedor').html('<option value>Seleccione RTN</option>');
           $('#Direccion_Proveedor').val('Seleccione RTN');
           $('#Telefono_Proveedor').val('Seleccione RTN');

      }});
    });
   
  function RefrescaProducto(){
    var ip = [];
    var i = 0;
    $('.contadorfilas').each(function(index, element){
      i++;
      ip.push({
          id_pro: $(this).val()
        });
      });
    if(i != ''){
      $('#submit').removeAttr('disabled', 'disabled');
    }else{
      $('#submit').attr('disabled', 'disabled');
    }
    if(i == 12){
      $('.blo').attr('disabled', 'disabled');
    }
    if(i <  12){
      $('.blo').removeAttr('disabled', 'disabled');
       
      }
    }

  function agregarProducto(){
            var newtr = '<tr class="item" data-id="">';//Obtengo en el tr el Id
            newtr = newtr + '<td class="contadorfilas"><input type="hidden" name="Cod_Detalle[]"></td><td><input type="text" class="form-control codigo" name="Producto[]" id="Producto[]" required ></td><td><input class="form-control Descripcion"  type="text" id="Descripcion[]" name="Descripcion[]" required ></td><td><input class="form-control text-center Cantidad" maxlength="4"  type="text" id="Cantidad[]" name="Cantidad[]" value ="1" onkeypress="return int(event)"   onChange="Calcular(this);" required/></td><td><input class="form-control text-right Precio" maxlength="10"  type="text" id="Precio[]" name="Precio[]" value ="0" onChange="Calcular(this);" required /></td><td><input class="form-control text-right Subtotal" type="text" id="Subtotal[]" name="Subtotal[]" value ="0"  onChange="Calcular(this);" required onFocus="this.blur()" readonly/></td>';
            newtr = newtr + '<td><button type="button" class="btn btn-danger btn-xs remove-item" ><i class="fa fa-times"></i></button></td></tr>';
            $('#ProSelected').append(newtr); //Agrego el Producto al tbody de la Tabla con el id=ProSelected

            $('.codigo').focus();

            RefrescaProducto(); //Refresco Productos
            
            $('.remove-item').off().click(function(e){
                var total = document.getElementById("total");
                total.innerHTML = parseFloat(total.innerHTML) - parseFloat(this.parentNode.parentNode.childNodes[3].childNodes[0].value);
                $(this).parent('td').parent('tr').remove(); //En accion elimino el Producto de la Tabla
                if ($('#ProSelected tr').length == 0)
                $('#ProSelected .no-item').slideDown(300);
                RefrescaProducto();
                
                Calcular(e.target);
                });

                $('.contadorfilas').off().change(function(e){
                RefrescaProducto();
            
                }); 
            }

          function Calcular(ele){
            var cantidad = 0, precio = 0, subtotal = 0;
            var tr = ele.parentNode.parentNode;
            var nodes = tr.childNodes;
        
            for (var x = 0; x < nodes.length; x++) {
                
                if (nodes[x].firstChild.id == 'Cantidad[]'){
                    cantidad = parseFloat(nodes[x].firstChild.value,10);
                }
                if (nodes[x].firstChild.id == 'Precio[]'){
                    precio = parseFloat(nodes[x].firstChild.value,10);
                }
                if (nodes[x].firstChild.id == 'Subtotal[]'){
                    anterior = nodes[x].firstChild.value;
                    subtotal = parseFloat((precio*cantidad),10);
                    nodes[x].firstChild.value = subtotal.toFixed(2);
                }        
            }
            
            if (total.innerHTML === 'NaN') {
             total.innerHTML = (parseFloat(total.innerHTML)+ 0).toFixed(2);
              
            }


            if (total.innerHTML != 'NaN') {   
            total.innerHTML = (parseFloat(total.innerHTML)+ subtotal - anterior).toFixed(2);
            }

            var to = document.querySelector('#total').innerText;
            var input_to = document.querySelector('input[name="Total"]');
             input_to.value = to;
          }
          
          function int(e){
          tecla = (document.all) ? e.keyCode : e.which;
            if (tecla==8){
               return true;
             }
            patron =/^[0-9]+$/;
            tecla_final = String.fromCharCode(tecla);
               return patron.test(tecla_final);
           }      

</script>