<?php
$title = 'Boleta de compra';
$this->headTitle($title);

$Fecha_Emision =$form->get('Fecha_Emision');
$Fecha_Emision->setAttribute('readonly', 'readonly');

$Consecutivo_Actual_Establ=$form->get('Consecutivo_Actual_Establ');
$Consecutivo_Actual_Establ->setAttribute('readonly', 'readonly');

$Consecutivo_Actual_Punto=$form->get('Consecutivo_Actual_Punto');
$Consecutivo_Actual_Punto->setAttribute('readonly', 'readonly');

$Consecutivo_Actual_Tipo=$form->get('Consecutivo_Actual_Tipo');
$Consecutivo_Actual_Tipo->setAttribute('readonly', 'readonly');

$Consecutivo_Actual_Correlativo=$form->get('Consecutivo_Actual_Correlativo');
$Consecutivo_Actual_Correlativo->setAttribute('readonly', 'readonly');

$Sucursal=$form->get('Sucursal');
$Sucursal->setAttribute('disabled', 'disabled');

$Autorizacion_Sar=$form->get('Autorizacion_Sar');
$Autorizacion_Sar->setAttribute('readonly', 'readonly');

$Nombre_Proveedor=$form->get('Nombre_Proveedor');
$Nombre_Proveedor->setAttribute('readonly', 'readonly');

$Direccion_Proveedor=$form->get('Direccion_Proveedor');
$Direccion_Proveedor->setAttribute('readonly', 'readonly');

$Telefono_Proveedor=$form->get('Telefono_Proveedor');
$Telefono_Proveedor->setAttribute('readonly', 'readonly');

$RTN_View=$form->get('RTN_View');
$RTN_View->setAttribute('readonly', 'readonly');

$Subtotal=$form->get('Subtotal');

$TotalView=$form->get('TotalView');

$cantidad_letras=$form->get('cantidad_letras');

$No_Registro_Sag=$form->get('No_Registro_Sag');
$No_Registro_Sag->setAttribute('readonly', 'readonly');

$No_Orden_Compra_Exenta=$form->get('No_Orden_Compra_Exenta');
$No_Orden_Compra_Exenta->setAttribute('readonly', 'readonly');

$No_Constancia_Registro_Exonerado=$form->get('No_Constancia_Registro_Exonerado');
$No_Constancia_Registro_Exonerado->setAttribute('readonly', 'readonly');


$Usuario=$form->get('Usuario')->setValue($this->identity()['Cod_Usuario']);
$Usuario->setAttribute('readonly', 'readonly');


$form->prepare();
?>                                              
<section>
    <div class="container-fluid">
          <div class="container">
            <table>
                <tbody>
                    <tr>
                        <td  style= "width:35%;"><img src="<?= $this->basePath('img/logoarmeria.png') ?>" class="img-responsive" style="height:40%; width:40%;display: block;margin-right: auto;margin-left:0;"></td>
                        <td style="text-align:center;width:30%">
                          <strong>FUERZAS ARMADAS DE HONDURAS</strong><br>
                          <strong>INSTITUTO DE PREVISIÓN MILITAR(IPM)</strong><br>
                          <strong>LA ARMERIA</strong><br>
                          <strong>RTN 08019003238214</strong><br>
                        </td>
                         <td  style= "width:35%;"><img src="<?= $this->basePath('img/logoIPM.png') ?>" class="img-responsive" style="height:20%; width:20%;display: block;margin-right: auto;margin-left:80%;"></td>
                    </tr>
                </tbody>
            </table><br>
            <table>
                <tbody>
                    <tr>
                        <td  style="text-align:left;width:40%">
                          <label>IPM :Colonia Luis landa Blvd Centro America</label><br>
                          <label>Contiguo a IMPREMA Fco. Morazán, Honduras</label><br>
                          <label>Tel: 504 2239-1441 meza@grupoipm.hn</label>
                        </td>
                        <td style="text-align:left;width:40%">
                          <?php foreach ($Suc as $g) : ?>
                          <label><?= $this->escapeHtml($g->Direccion) ?></label><br>
                          <label><?= $this->escapeHtml($g->Telefono) ?></label><br>
                          <label><?= $this->escapeHtml($g->Correo) ?></label>
                        <?php endforeach; ?>
                        </td>
                    </tr>
                </tbody>
            </table><br>
                <h5 style="text-align: center;font-weight: bold">BOLETA DE COMPRA</h5>
            <table>
                <thead>
                  <tr>
                    <th></th>
                    <th  style="text-align: center" colspan="4">No. Documento fiscal</th>
                  </tr>
                </thead>
                <tbody><?php foreach ($Cai as $b) : ?>
                  <tr>
                      <td style="width:30%"><strong>CAI:<?= $this->escapeHtml($b->Cai) ?></strong></td>
                      <td style="width:8%"><?= $this->formElement($Consecutivo_Actual_Establ)?></td>
                      <td style="width:8% "><?= $this->formElement($Consecutivo_Actual_Tipo)?></td>
                      <td style="width:8%"><?= $this->formElement($Consecutivo_Actual_Punto)?></td>
                      <td style="width:10%"><?= $this->formElement($Consecutivo_Actual_Correlativo)?></td>
                  </tr><?php endforeach;?>
                </tbody>
            </table><br>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <?= $this->formLabel($Nombre_Proveedor) ?>
                            <?= $this->formElement($Nombre_Proveedor) ?>
                        </div>
                    </div>

                    <div class="col-md-8">
                        <div class="form-group">
                            <?= $this->formLabel($RTN_View) ?>
                            <?= $this->formElement($RTN_View) ?>
                        </div>
                    </div>
                </div><br>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                             <?= $this->formLabel($Direccion_Proveedor) ?>
                            <?= $this->formElement($Direccion_Proveedor) ?>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                           <?= $this->formLabel($Telefono_Proveedor) ?>
                           <?= $this->formElement($Telefono_Proveedor) ?>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                           <label>Fecha Emisión</label>
                           <?= $this->formElement($Fecha_Emision) ?>
                        </div>
                    </div>
                </div><br>
                <table  class="table table-bordered">
                <thead style="background-color:#E6E6FA">
                  <tr>
                    <th>No.</th>
                    <th>Código producto</th>
                    <th colspan="2">Descripcion</th>
                    <th>Cantidad</th>
                    <th>Precio</th>
                    <th>Importe</th>
                  </tr>
                </thead>
                <tbody><?php  
                     $count=1;
                     $Importe=0;
                     foreach ($Detalle as $a) : 
                      ?>
                    <tr>
                      <td><?= $count ?></td>
                      <td><?= $this->escapeHtml($a->Producto) ?></td>
                      <td colspan="2"><?= $this->escapeHtml($a->Descripcion) ?></td>
                      <td><?= $this->escapeHtml($a->Cantidad)?></td>
                      <td><?= $this->escapeHtml($a->Precio) ?></td>
                      <td class="text-right">
                      <?php
                          $cantidad = $this->escapeHtml($a->Cantidad);
                          $precio = $this->escapeHtml($a->Precio);
                          $Importe = $cantidad*$precio;
                             echo 'L. '.number_format($Importe, 2, ".", ",");
                      ?>
                      </td>
                    </tr><?php  
                          $count++;  
                      endforeach; 
                      ?>
                </tbody>
                <tfoot>
                  <tr>
                    <td colspan="6" class="text-right"><?= $this->formLabel($Subtotal)?></td>
                    <td class="text-right"><?=  $this->formElement($TotalView) ?></td>
                  </tr>
                  <tr>
                    <td colspan="6" class="text-right" ><?= 'Total'?>
                    <td><?= $this->formElement($TotalView) ?></td>
                  </tr>
                </tfoot>
            </table>
              <?= '<label>CANTIDAD EN:</label>'. $this->formElement($cantidad_letras)?>
            <h5>DATOS ADQUIRIENTE EXONERADO</h5>
                 <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <?= $this->formLabel($No_Registro_Sag) ?>
                            <?= $this->formElement($No_Registro_Sag) ?>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <?= $this->formLabel($No_Orden_Compra_Exenta) ?>
                            <?= $this->formElement($No_Orden_Compra_Exenta) ?>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <?= $this->formLabel($No_Constancia_Registro_Exonerado) ?>
                            <?= $this->formElement($No_Constancia_Registro_Exonerado) ?>
                        </div>
                    </div>
                </div>
            <table width="100%" class="table">
                <tbody>
                <?php foreach ($Sar as $a) : ?>
                    <tr>
                      <td>Rango Autorizado:<?= $this->escapeHtml($a->Consecutivo_Inicial_Establ."-".$a->Consecutivo_Inicial_Punto."-".$a->Consecutivo_Inicial_Tipo."-".$a->Consecutivo_Inicial_Correlativo)?> al <?= $this->escapeHtml($a->Consecutivo_Final_Establ."-".$a->Consecutivo_Final_Punto."-".$a->Consecutivo_Final_Tipo."-".$a->Consecutivo_Final_Correlativo) ?></td>
                      <td>Fecha límite:<?= $this->escapeHtml($a->Fecha_Limite) ?></td>
                      <td>Fecha de impresión:<?= date('y-m-d H:i:s')?></td>
                     </tr>
                  <?php endforeach; ?>
                </tbody>
            </table>
            <table width="100%">
                <thead>
                    <tr>
                        <th>Usuario</th>
                    </tr>
                </thead>
                <tbody><?php foreach ($user as $u) : ?>
                    <tr>
                      <td><label>COD:<?= $this->escapeHtml($u->Cod_Usuario)?>-<?= $this->escapeHtml($u->Usuario)?></label></td>
                    </tr><?php endforeach; ?>
                </tbody>
                <tfoot>
                  <tr>
                    <td>Original: Contribuyente adquiriente</td>
                    <td>Copia: proveedor</td>
                  </tr>
                </tfoot>
            </table><br>
            <table width="100%">
                <tbody> 
                    <tr>
                      <td></td>
                      <td width="30%">
                        <a type="button"  target="_blank" class="btn btn-danger btn-md btn-block"  href="<?= $this->url('boletacompra/pdf',['Cod_Boleta_Compra'=>$Cod_Boleta_Compra])?>"><i class="fa fa-file-pdf-o"></i>PDF</a>
                      </td>
                      <td></td>
                    </tr>
                 </tbody>
            </table><br>
         </div>
    </div>
</section>