<?php
$title = 'Listado de boletas de compra';
$this->headTitle($title);
?>
<div class="container">
    <h4 class="text-center"><?= $this->escapeHtml($title) ?></h4>

    <table class="display"    id="example"  style="width:100%">
      <thead style="background-color:brown;color:white;">
        <tr>
          <th>Sucursal</th>
          <th>c&oacute;digo  boleta</th>
          <th>N&uacute;mero de documento fiscal</th>
          <th>Autorización SAR</th>
          <th>Fecha  Emisi&oacute;n</th>
          <th>Acci&oacute;n1</th>
          <th>Acci&oacute;n2</th>
        </tr>
      </thead>
      <tbody>
      <?php foreach ($Boleta as $a) : ?>
      <tr>
        <td><?= $this->escapeHtml($a->Nombre_Sucursal) ?></td>
        <td><?= $this->escapeHtml($a->Cod_Boleta) ?></td>
        <td><?= $this->escapeHtml($a->Autorizacion_sar) ?></td>
        <td><?= $this->escapeHtml($a->Consecutivo_Actual_Establ."-".$a->Consecutivo_Actual_Punto."-".$a->Consecutivo_Actual_Tipo."-".$a->Consecutivo_Actual_Correlativo)?></td>
        <td><?= $this->escapeHtml($a->Fecha_Emision) ?></td>
        <td>
            <a type="button"  class=" btn btn-info btn-md"  href="<?= $this->url('boletacompra/detalle',['Cod_Boleta'=>$a->Cod_Boleta])?>"><i class="fa fa-eye-slash"></i></a>
        </td>
        <td>
            <a type="button"  target="_blank" class="btn btn-danger btn-md"  href="<?= $this->url('boletacompra/pdf',['Cod_Boleta'=>$a->Cod_Boleta])?>"><i class="fa fa-file-pdf-o"></i>PDF</a>      
        </td>     
      </tr>
      <?php endforeach; ?>
     </tbody>
</table>
</div>
<script type="text/javascript">
 $(document).ready(function() {
    $('#example').DataTable({
    "language": {
      "url": "datatables/js/Spanish.json"
    }
    });
   });
</script>