<?php
$this->doctype();
$Fecha_Emision =$form->get('Fecha_Emision');
$Fecha_Emision->setAttribute('readonly', 'readonly');

$Consecutivo_Actual_Establ=$form->get('Consecutivo_Actual_Establ');
$Consecutivo_Actual_Establ->setAttribute('readonly', 'readonly');

$Consecutivo_Actual_Punto=$form->get('Consecutivo_Actual_Punto');
$Consecutivo_Actual_Punto->setAttribute('readonly', 'readonly');

$Consecutivo_Actual_Tipo=$form->get('Consecutivo_Actual_Tipo');
$Consecutivo_Actual_Tipo->setAttribute('readonly', 'readonly');

$Consecutivo_Actual_Correlativo=$form->get('Consecutivo_Actual_Correlativo');
$Consecutivo_Actual_Correlativo->setAttribute('readonly', 'readonly');

$Sucursal=$form->get('Sucursal');
$Sucursal->setAttribute('disabled', 'disabled');

$Autorizacion_Sar=$form->get('Autorizacion_Sar');
$Autorizacion_Sar->setAttribute('readonly', 'readonly');

$Nombre_Proveedor=$form->get('Nombre_Proveedor');
$Nombre_Proveedor->setAttribute('readonly', 'readonly');

$Direccion_Proveedor=$form->get('Direccion_Proveedor');
$Direccion_Proveedor->setAttribute('readonly', 'readonly');

$Telefono_Proveedor=$form->get('Telefono_Proveedor');
$Telefono_Proveedor->setAttribute('readonly', 'readonly');

$RTN_Proveedor=$form->get('RTN_Proveedor');
$RTN_Proveedor->setAttribute('readonly', 'readonly');

$No_Registro_Sag=$form->get('No_Registro_Sag');
$No_Registro_Sag->setAttribute('readonly', 'readonly');

$No_Orden_Compra_Exenta=$form->get('No_Orden_Compra_Exenta');
$No_Orden_Compra_Exenta->setAttribute('readonly', 'readonly');

$No_Constancia_Registro_Exonerado=$form->get('No_Constancia_Registro_Exonerado');
$No_Constancia_Registro_Exonerado->setAttribute('readonly', 'readonly');

$TotalView=$form->get('TotalView');


$Usuario=$form->get('Usuario')->setValue($this->identity()['Cod_Usuario']);
$Usuario->setAttribute('readonly', 'readonly');

?>
<html lang="en">
<head>
      <meta charset="utf-8">
      <title>Boleta de compra |La Armería</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">   
       <style type="text/css">
          table {
           width: 100%;
          }
          td {
           text-align: left;
           vertical-align: top;
           font-size:x-small;
          }
          th{
            text-align: left;
            vertical-align: top;
            font-weight:bold;
            font-size:x-small;
          }
          label {
           display: inline-block;
           max-width: 100%;
           margin-bottom: 3px;
           font-weight:bold;
           font-size:x-small;
          }
          input{
           text-align: center;
           display: block;
           width:100%;
           height: 15px;
           padding:1px 3px;
           font-size:xx-small;
           line-height: 1.42857143;
           color: #000;
           background-color: #fff;
           background-image: none;
           border: 1px solid #ccc;
           border-radius: 3px;
          -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);
          box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);
          -webkit-transition: border-color ease-in-out .15s, -webkit-box-shadow ease-in-out .15s;
          -o-transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
          transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
        }
        select{
           display: block;
           width: 100%;
           height: 16px;
           padding: 1px 3px;
           text-align: center;
           font-size:xx-small;
           line-height: 1.42857143;
           color: #000;
           background-color: #fff;
           border: 1px solid #ccc;
           border-radius: 3px;
          -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);
          box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);
          -webkit-transition: border-color ease-in-out .15s, -webkit-box-shadow ease-in-out .15s;
          -o-transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
          transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
        }
         
        .pro{ 
          padding: .35em .625em .75em;
          margin: 0 2px;
          width:100%;
          border: 1px solid #c0c0c0;
        }
        .pro-th{ 
         background-color: #E6E6FA;
         width: 100%;
         height: 16px;
        }
       </style>
</head>
<body>
<section>
    <div>
          <table>
                <tbody>
                    <tr>
                        <td style= "width:30%;"><img src="http://laarmeria/img/logoarmeria.png" style="height:40px; width:100px;display: block;margin-right: auto;margin-left: auto;"></td>
                        <td style="text-align:center;width:40%">
                             <strong>FUERZAS ARMADAS DE HONDURAS</strong><br>
                             <strong>INSTITUTO DE PREVISIÓN MILITAR(IPM)</strong><br>
                             <strong>LA ARMERIA</strong><br>
                             <strong>RTN 08019003238214</strong><br>
                             <strong>LA ARMERIA AEROPUERTO</strong><br>
                        </td>
                        <td  style= "width:30%;"><img src="http://laarmeria/img/logoIPM.png" style="height:60px; width:60px;display: block;margin-right:auto;margin-left:60%;"></td>
                    </tr>
                </tbody>
            </table>
            <table class="pad">
                <tbody>
                    <tr>
                        <td  style="text-align:left;width:40%">
                          <label>IPM :Colonia Luis landa Blvd Centro America</label><br>
                          <label>Contiguo a IMPREMA Fco. Morazán, Honduras</label><br>
                          <label>Tel: 504 2239-1441 meza@grupoipm.hn</label>
                        </td>
                        <td style="text-align:left;width:40%">
                          <?php foreach ($Suc as $g) : ?>
                          <label><?= $this->escapeHtml($g->Direccion) ?></label><br>
                          <label><?= $this->escapeHtml($g->Telefono) ?></label><br>
                          <label><?= $this->escapeHtml($g->Correo) ?></label>
                        <?php endforeach; ?>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div style="text-align: center;font-weight: bold">BOLETA DE COMPRA</div>
            <table>
                <thead>
                  <tr>
                    <th></th>
                    <th style="text-align: center">No.</th>
                    <th>Documento</th>
                    <th>Fiscal</th>
                    <th></th>
                    <th></th>
                  </tr>
                </thead>
                <tbody><?php foreach ($Cai as $b) : ?>
                  <tr>
                      <td style="width:30%"><strong>CAI: <?= $this->escapeHtml($b->Cai) ?></strong></td>
                      <td style="width:8%"><?= $this->formElement($Consecutivo_Actual_Establ)?></td>
                      <td style="width:8% "><?= $this->formElement($Consecutivo_Actual_Tipo)?></td>
                      <td style="width:8%"><?= $this->formElement($Consecutivo_Actual_Punto)?></td>
                      <td style="width:10%"><?= $this->formElement($Consecutivo_Actual_Correlativo)?></td>
                      <td style="width:5%"></td>
                  </tr><?php endforeach;?>
                </tbody>
            </table>
            <table>
                <thead>
                  <tr>
                    <th><?= $this->formlabel($Nombre_Proveedor)?></th>
                    <th><?= $this->formLabel($RTN_Proveedor)?></th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td style="width:30%"><?= $this->formElement($Nombre_Proveedor)?></td>
                    <td style="width:70%"><?= $this->formElement($RTN_Proveedor)?></td>  
                  </tr>
                </tbody>
            </table>
            <table>
                <thead>
                  <tr>
                    <th style="width:70%"><?= $this->formlabel($Direccion_Proveedor)?></th>
                    <th style="width:15%"><?= $this->formLabel($Telefono_Proveedor)?></th>
                    <th style="width:15%">Fecha Emisión</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td><?= $this->formElement($Direccion_Proveedor)?></td>
                    <td><?= $this->formElement($Telefono_Proveedor)?></td>
                    <td><?= $this->formElement($Fecha_Emision)?></td>
                  </tr>
                </tbody>
            </table>
            <table  class="pro">
                <thead class="pro-th">
                  <tr>
                    <th style="text-align:center;">No.</th>
                    <th style="text-align:center;">Código producto</th>
                    <th style="text-align:center;">Descripción</th>
                    <th style="text-align:center;">Cantidad</th>
                    <th style="text-align:center;">Precio</th>
                    <th style="text-align:center;">Importe</th>
                  </tr>
                </thead>
                 <tbody><?php  
                     $count=1;
                     $Importe=0;
                     foreach ($Detalle as $a) : 
                      ?>
                    <tr>
                      <td><?= $count ?></td>
                      <td><?= $this->escapeHtml($a->Producto) ?></td>
                      <td><?= $this->escapeHtml($a->Descripcion) ?></td>
                      <td><?= $this->escapeHtml($a->Cantidad)?></td>
                      <td style="text-align:right;"><?= $this->escapeHtml($a->Precio) ?></td>
                      <td  style="text-align:right;">
                      <?php
                          $cantidad = $this->escapeHtml($a->Cantidad);
                          $precio = $this->escapeHtml($a->Precio);
                          $Importe = $cantidad*$precio;
                             echo '<label>L. </label>' . number_format($Importe, 2, ".", ",");
                      ?>
                      </td>
                    </tr><?php  
                          $Importe+$Importe; 
                          $count++;
                      endforeach; 
                      ?>
                </tbody>
                <tfoot>
                  <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>Subtotal</td>
                    <td><label>L. </label></td>
                  </tr>
                  <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td><?= '<label>Total</label>'?></td>
                    <td><label>L. </label></td>
                  </tr>
                </tfoot>
            </table>
            <h5>DATOS DEL ADQUIRIENTE EXONERADO</h5>
            <table>
                <tbody>
                  <tr>
                    <td><?= $this->formLabel($No_Registro_Sag)?><?= $this->formElement($No_Registro_Sag)?></td>
                    
                  </tr>
                   <tr>
                    <td><?= $this->formLabel($No_Orden_Compra_Exenta)?><?= $this->formElement($No_Orden_Compra_Exenta)?></td>
                  </tr>
                   <tr>
                    <td><?= $this->formLabel($No_Constancia_Registro_Exonerado)?><?= $this->formElement($No_Constancia_Registro_Exonerado)?></td>
                  </tr>
                </tbody>
            </table>
            <table>
                <thead>
                  <tr>
                    <th></th>
                    <th></th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                <?php foreach ($Sar as $a) : ?>
                    <tr>
                      <td>Rango Autorizado:<?= $this->escapeHtml($a->Consecutivo_Inicial_Establ."-".$a->Consecutivo_Inicial_Punto."-".$a->Consecutivo_Inicial_Tipo."-".$a->Consecutivo_Inicial_Correlativo)?> al <?= $this->escapeHtml($a->Consecutivo_Final_Establ."-".$a->Consecutivo_Final_Punto."-".$a->Consecutivo_Final_Tipo."-".$a->Consecutivo_Final_Correlativo) ?></td>
                      <td>Fecha límite:<?= $this->escapeHtml($a->Fecha_Limite) ?></td>
                      <td>Fecha de impresión:<?= date('y-m-d H:i:s')?></td>
                     </tr>
                  <?php endforeach; ?>
                </tbody>
            </table>
            <table>
                <thead>
                    <tr>
                        <th>Usuario</th>
                    </tr>
                </thead>
                <tbody><?php foreach ($user as $u) : ?>
                    <tr>
                      <td><label>COD:<?= $this->escapeHtml($u->Cod_Usuario)?>-<?= $this->escapeHtml($u->Usuario)?></label></td>
                    </tr><?php endforeach; ?>
                </tbody>
                <tfoot>
                    <td>Original: contribuyente adquiriente</td>
                    <td>Copia: Proveedor</td>
                </tfoot>
            </table>
        </div>
     </section>
  </body>
</html>