<?php
$title = 'Editar registro de conductor';
$this->headTitle($title);

$Cod_Conductor=$form->get('Cod_Conductor');
$Cod_Conductor->setAttribute('class', 'form-control');
$Cod_Conductor->setAttribute('readonly', 'readonly');


$Nombres_Conductor=$form->get('Nombres_Conductor');
$Nombres_Conductor->setAttribute('class', 'form-control');

$Apellidos_Conductor=$form->get('Apellidos_Conductor');
$Apellidos_Conductor->setAttribute('class', 'form-control');

$Licencia_Conducir=$form->get('Licencia_Conducir');
$Licencia_Conducir->setAttribute('class','form-control');
$Licencia_Conducir->setAttribute('placeholder', '0000000000000');

$Estado=$form->get('Estado');
$Estado->setAttribute('class','form-control');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-success btn-lg btn-block');

//$form->setAttribute('action', $this->url('departamento/edit', ['Cod_Departamento'=> $Cod_Departamento]));

$form->prepare();
?>
<section id="cover">
    <div id="cover-caption">
        <div id="container" class="container">
        <h4 class="text-center"><i class="fa fa-id-card fa-md" aria-hidden="true"></i><?= $this->escapeHtml($title) ?></h4>
            <div class="row justify-content-center">
                <div class="col-md-12 offset-md-7">
                    <div class="info-form">
                    <?= $this->form()->openTag($form)?>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <?= $this->formLabel($Cod_Conductor) ?>
                                    <?= $this->formElement($Cod_Conductor) ?>
                                    <?= $this->formElementErrors()->render($Cod_Conductor, ['class' => 'help-inline  text-danger']) ?>
                                </div>


                                <div class="form-group">
                                    <?= $this->formLabel($Nombres_Conductor) ?>
                                    <?= $this->formElement($Nombres_Conductor) ?>
                                    <?= $this->formElementErrors()->render($Nombres_Conductor, ['class' => 'help-inline  text-danger']) ?>
                                </div>

                                <div class="form-group">
                                    <?= $this->formLabel($Apellidos_Conductor) ?>
                                    <?= $this->formElement($Apellidos_Conductor) ?>
                                    <?= $this->formElementErrors()->render($Apellidos_Conductor, ['class' => 'help-inline  text-danger']) ?>
                                </div>

                                <div class="form-group">
                                    <?= $this->formLabel($Licencia_Conducir) ?>
                                    <?= $this->formElement($Licencia_Conducir) ?>
                                    <?= $this->formElementErrors()->render($Licencia_Conducir, ['class' => 'help-inline  text-danger']) ?>
                                </div>

                                <div class="form-group">
                                    <?= $this->formLabel($Estado) ?>
                                    <?= $this->formElement($Estado) ?>
                                    <?= $this->formElementErrors()->render($Estado, ['class' => 'help-inline  text-danger']) ?>
                                </div>
                                <?= $this->formSubmit($submit)?> 
                            </div>
                        </div>
                    <?= $this->form()->closeTag()?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>