<?php
$title = 'Listado de Conductores';
$this->headTitle($title);
?>
<div class="container">
<h4 class="text-center"><?= $this->escapeHtml($title) ?></h4>
    <div>
      <p>
        <a class="btn btn-outline-info float-right"  role="button" href="<?= $this->url('conductor/add')?>"><i class="fa fa-plus-circle"></i>Agregar</a>
      </p>
    </div>
    <table class="table table-hover"  id="example"  style="width:100%">
      <thead style="background-color:brown;color:white;" rowspan="2">
        <tr>
          <th>c&oacute;digo de  conductor</th>
          <th>Nombres </th>
          <th>Apellidos</th>
          <th>Licencia de conducir</th>
          <th>Estado</th>
          <th>Fecha de ingreso</th>
          <th>Fecha de actualizaci&oacute;n</th>
          <th>Acci&oacute;n</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($conductor as $cond) : ?>
        <tr>
          <td><?= $this->escapeHtml($cond->Cod_Conductor) ?></td>
          <td><?= $this->escapeHtml($cond->Nombres_Conductor) ?></td>
          <td><?= $this->escapeHtml($cond->Apellidos_Conductor) ?></td>
          <td><?= $this->escapeHtml($cond->Licencia_Conducir) ?></td>
          <td><?= $this->escapeHtml($cond->Estado) ?></td>
          <td><?= $this->escapeHtml($cond->Fecha_Ingreso) ?></td>
          <td><?= $this->escapeHtml($cond->Fecha_Actualizacion) ?></td>
          <td>
             <a type="button" class=" btn btn-primary btn-sm"  href="<?= $this->url('conductor/edit',['Cod_Conductor'=>$cond->Cod_Conductor])?>"><i class="fa fa-pencil"></i></a>
          </td>
        </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
    </div>
<script type="text/javascript">
 $(document).ready(function() {
    $('#example').DataTable({
    "language": {
      "url": "datatables/js/Spanish.json"
    }
    });
   });
</script>