<?php
$title = 'Clientes';
$this->headTitle($title);
?>
<div class="container">
<h4 class="text-center"><?= $this->escapeHtml($title) ?></h4>
    <div>
      <p>
        <a class="btn btn-outline-info float-right"  role="button" href="<?= $this->url('cliente/add')?>"><i class="fa fa-plus-circle"></i>Agregar</a>
      </p>
    </div>
    <table class="table table-hover"    id="example"  style="width:100%">
      <thead class="thead-light" style="">
        <tr>
          <th>c&oacute;digo de  conductor</th>
          <th>Nombres </th>
          <th>Apellidos</th>
          <th>RTN/DNI</th>
          <th>Fecha de ingreso</th>
          <th>Fecha de actualizaci&oacute;n</th>
          <th>Acci&oacute;n</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($cliente as $cond) : ?>
        <tr>
          <td><?= $this->escapeHtml($cond->Cod_Cliente) ?></td>
          <td><?= $this->escapeHtml($cond->Nombres_Cliente) ?></td>
          <td><?= $this->escapeHtml($cond->Apellidos_Cliente) ?></td>
          <td><?= $this->escapeHtml($cond->RTN_DNI) ?></td>
          <td><?= $this->escapeHtml($cond->Fecha_Ingreso) ?></td>
          <td><?= $this->escapeHtml($cond->Fecha_Actualizacion) ?></td>
          <td>
             <a type="button" class=" btn btn-primary btn-block btn-sm"  href="<?= $this->url('cliente/edit',['Cod_Cliente'=>$cond->Cod_Cliente])?>"><i class="fa fa-pencil">Editar</i></a>
          </td>
        </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
    </div>
<script type="text/javascript">
 $(document).ready(function() {
    $('#example').DataTable({
    "language": {
      "url": "datatables/js/Spanish.json"
    }
    });
   });
</script>