<?php
$title = 'Editar Artículo';
$this->headTitle($title);

$Cod_Producto=$form->get('Cod_Producto');
$Cod_Producto->setAttribute('class', 'form-control');
$Cod_Producto->setAttribute('readonly', 'readonly');

$Nombre_Producto=$form->get('Nombre_Producto');
$Nombre_Producto->setAttribute('class', 'form-control');

$Descripcion=$form->get('Descripcion');
$Descripcion->setAttribute('class', 'form-control');

$Precio=$form->get('Precio');
$Precio->setAttribute('class', 'form-control  text-right');

$Cantidad=$form->get('Cantidad');
$Cantidad->setAttribute('class', 'form-control text-right');

$Sucursal=$form->get('Sucursal');
$Sucursal->setAttribute('class', 'form-control text-center');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-success  btn-block');

//$form->setAttribute('action', $this->url('productos/edit', ['Cod_Producto'=> $Cod_Producto]));

$form->prepare();
?>
<section id="cover">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 col-md-6">
                <div class="card">
                    <div class="card-header">
                         <h4 class="text-center"><i class="fa fa-shopping-cart" aria-hidden="true"></i><?= $this->escapeHtml($title) ?></h4>
                    </div>
                    <div class="card-body">
                        <?=  $this->form()->openTag($form)?>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <?= $this->formLabel($Cod_Producto) ?>
                                    <?= $this->formElement($Cod_Producto) ?>
                                    <?= $this->formElementErrors()->render($Cod_Producto, ['class' => 'help-inline  text-danger']) ?>
                                </div> 
                            </div> 
                        </div>
                        <div class="row">
                             <div class="col-md-6">
                                <div class="form-group">
                                    <?= $this->formLabel($Nombre_Producto) ?>
                                    <?= $this->formElement($Nombre_Producto) ?>
                                    <?= $this->formElementErrors()->render($Nombre_Producto, ['class' => 'help-inline  text-danger']) ?>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <?= $this->formLabel($Sucursal) ?>
                                    <?= $this->formElement($Sucursal) ?>
                                    <?= $this->formElementErrors()->render($Sucursal, ['class' => 'help-inline  text-danger']) ?>
                                </div> 
                            </div>    
                        </div>
                         <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <?= $this->formLabel($Descripcion) ?>
                                    <?= $this->formElement($Descripcion) ?>
                                    <?= $this->formElementErrors()->render($Descripcion, ['class' => 'help-inline  text-danger']) ?>
                                </div>
                                   
                            </div>
                        </div>
                        <div class="row">
                             <div class="col-md-6">
                                <div class="form-group">
                                    <?= $this->formLabel($Precio)?>
                                    <?= $this->formElement($Precio) ?>
                                    <?= $this->formElementErrors()->render($Precio, ['class' => 'help-inline  text-danger']) ?>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <?= $this->formLabel($Cantidad) ?>
                                    <?= $this->formElement($Cantidad) ?>
                                    <?= $this->formElementErrors()->render($Cantidad, ['class' => 'help-inline  text-danger']) ?>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                   <?= $this->formSubmit($submit)?>  
                                </div> 
                            </div>
                        </div>
                        <?= $this->form()->closeTag() ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>