<?php
$title = 'Artículos';
$this->headTitle($title);
?>
<div class="container">
  <h4  class="text-center"><?= $this->escapeHtml($title) ?></h4>
    <p>
      <a class="btn btn-outline-info float-right"  role="button" href="<?= $this->url('productos/add')?>">
        <i class="fa fa-plus-circle"></i>Agregar</a>
    </p>
     <table class="table table-hover"    id="example"  style="width:100%">
      <thead class="thead-light">
        <tr>
          <th>C&oacute;digo</th>
          <th>Nombre</th>
          <th>Descripci&oacute;n</th>
          <th>Precio</th>
          <th>Cantidad</th>
          <th>Sucursal</th>
          <th>Fecha de ingreso</th>
          <th>Acci&oacute;n</th>
        </tr>
      </thead>
      <tbody>
      <?php foreach ($product as $pro) : ?>
        <tr>
          <td><?= $this->escapeHtml($pro->Cod_Producto) ?></td>
          <td><?= $this->escapeHtml($pro->Nombre_Producto) ?></td>
          <td><?= $this->escapeHtml($pro->Descripcion) ?></td>
          <td>
          <?Php
              $Pre = $this->escapeHtml($pro->Precio);
              echo 'L.'.number_format($Pre, 2, ".", ",");
           ?>
          </td>
          <td class="text-center"><?= $this->escapeHtml($pro->Cantidad)+0?></td>
          <td class="text-center"><?= $this->escapeHtml($pro->Sucursal) ?></td>
          <td><?= $this->escapeHtml($pro->Fecha_Ingreso) ?></td>
          <td> 
            <a type="button" class=" btn btn-primary btn-block btn-sm"  href="<?=$this->url('productos/edit',['Cod_Producto'=>$pro->Cod_Producto])?>"><i class="fa fa-pencil">Editar</i></a>      
          </td>
        </tr>
       <?php endforeach; ?>
      </tbody>
    </table>
</div>
<script type="text/javascript">
 $(document).ready(function() {
    $('#example').DataTable({
    "language": {
      "url": "datatables/js/Spanish.json"
    }
    });
   });
</script>


  


  
  
  
        
        
