<div class="container-fluid">
    <div class="container">
       <div class="row">
            <div class="col-md-6">
                <p style="text-align: center; "><img src="<?= $this->basePath('img/logoarmeria.png') ?>" height="10%" width="40%" class="img-thumbnail img-responsive" /></p>
            </div>
            <div class="col-md-4">
                <p style="text-align: center; "><img src="<?= $this->basePath('img/logoIPM.png') ?>" height="20%" width="20%" class="img-thumbnail img-responsive" /></p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Comunicado N#1</h3>
                    </div>
                    <div class="card-body">
                        <p>
                            Contenido
                        </p>

                        <p><a class="btn btn-info pull-right" href="#" >Link1</a></p>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Comunicado N#2</h3>
                    </div>
                    <div class="card-body">
                        <p>
                        Contenido
                        </p>
                        <p><a class="btn btn-success pull-right" href="#">Link2</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
