<div class="container-fluid">
    <div class="container">
         <p style="text-align: center; "><img src="<?= $this->basePath('img/logo.PNG') ?>" height="150%" class="img-thumbnail img-responsive" /></p>
   </div>
   <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                   <h3 class="card-title">Comunicado N#1</h3>
                </div>
                <div class="card-body">
                <p>
                  Contenido
                </p>

                <p><a class="btn btn-info pull-right" href="http://modules.zendframework.com/" target="_blank">Link</a></p>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Comunicado N#2</h3>
                </div>
                <div class="card-body">
                <p>
                    Contenido
                    <p><a class="btn btn-success pull-right" href="https://laarmeria.hn/" target="_blank">Sitio Web</a></p>
                </p>  
                </div>
            </div>
        </div>
    </div>
</div>
