<?php
$title = 'Notas de débito';
$this->headTitle($title);
?>
<div class="container-fluid">
    <h4 class="text-center"><?= $this->escapeHtml($title) ?></h4>

    <table class="table table-hover"    id="example"  style="width:100%">
      <thead class="thead-light">
        <tr>
          <th>C&oacute;digo Nota de débito</th>
          <th>N&uacute;mero de documento fiscal</th>
          <th>Cliente</th>
          <th>RTN</th>
          <th>No. Correlativo Comprobante</th>
          <th>Cai Comprobante</th>
          <th>Fecha de Emisión Comprobante</th>
          <th>Fecha Emisi&oacute;n</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      <?php foreach ($Nota as $a) : ?>
      <tr class="text-center">
        <td><?= $this->escapeHtml($a->Cod_Nota) ?></td>
        <td><?= $this->escapeHtml($a->Consecutivo_Actual_Establ."-".$a->Consecutivo_Actual_Punto."-".$a->Consecutivo_Actual_Tipo."-".$a->Consecutivo_Actual_Correlativo)?></td>
        <td><?= $this->escapeHtml($a->Nombres_Cliente) ?></td>
        <td><?= $this->escapeHtml($a->Rtn_Dni) ?></td>
        <td><?= $this->escapeHtml($a->No_Correlativo)?></td>
        <td><?= $this->escapeHtml($a->Cai_Comprobante)?></td>
        <td><?= $this->escapeHtml($a->Fecha_Emision_Comprobante)?></td>
        <td><?= $this->escapeHtml($a->Fecha_Emision) ?></td>
        <td> <a type="button"  class=" btn btn-info btn-md"  href="<?= $this->url('notadebito/detalle',['Cod_Nota'=>$a->Cod_Nota])?>"><i class="fa fa-eye-slash"></i>Ver</a></td>
        <td> <a type="button" target="_blank" class=" btn btn-danger btn-md"  href="<?= $this->url('notadebito/pdf',['Cod_Nota'=>$a->Cod_Nota])?>"><i class="fa fa-file-pdf-o"></i>PDF</a></td>     
      </tr>
      <?php endforeach;?>
     </tbody>
</table>
</div>
<script type="text/javascript">
 $(document).ready(function() {
    $('#example').DataTable({
    "language": {
      "url": "datatables/js/Spanish.json"
    }
    });
   });
</script>